; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
boards_dir = .

[env:esp32-s3-devkitc-1-myboard]
platform = espressif32
board = esp32-s3-devkitc-1-myboard
framework = arduino
monitor_speed = 115200
upload_speed = 115200
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_flags = 
    ; -D DEVELOPMENT_MODE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I./include
    -I.             # Add this to allow finding ui/ui.h
    -I./lib         # Add this to find lvgl/lvgl.h
    ; -DVERSION=\"0.0.1-alpha\"
    -DBOARD_HAS_PSRAM
    -Wl,--print-memory-usage
    -Wl,-Map,firmware.map
    -Os
    -DCORE_DEBUG_LEVEL=0

lib_deps = 
    moononournation/GFX Library for Arduino@1.2.8
    lovyan03/LovyanGFX@^1.1.12
    https://github.com/Bodmer/TFT_Touch
    ; ../../M4Device
    git+https://github.com/ATC-Industries/M4Device.git
	Preferences
	gmag11/QuickEspNow @ ^0.6.2
    gmag11/QuickDebug
board_build.partitions = huge_app.csv
board_build.psram = enabled
