// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "../ui.h"

lv_obj_t *uic_PullHistoryScreenLabeldownloadPullHistoryButtonLabel;
lv_obj_t *uic_PullHistoryScreenButtondownloadPullHistoryButton;
lv_obj_t *uic_PullHistoryScreenButtondeletePullHistoryButton1;
lv_obj_t *uic_PullHistoryScreenLabeldeletePullHistoryButtonLabel;
lv_obj_t *uic_PullHistoryScreenButtondeletePullHistoryButton;
lv_obj_t *uic_PullHistoryScreenContainerButtonContainer;
lv_obj_t *uic_PullHistoryScreenPanelTablePanel;
lv_obj_t *ui_ScreenPullHistoryScreen = NULL;lv_obj_t *ui_PullHistoryScreenPanelTablePanel = NULL;lv_obj_t *ui_PullHistoryScreenContainerButtonContainer = NULL;lv_obj_t *ui_PullHistoryScreenButtondeletePullHistoryButton = NULL;lv_obj_t *ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel = NULL;lv_obj_t *ui_PullHistoryScreenButtondeletePullHistoryButton1 = NULL;lv_obj_t *ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1 = NULL;lv_obj_t *ui_PullHistoryScreenButtondownloadPullHistoryButton = NULL;lv_obj_t *ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel = NULL;
// event funtions
void ui_event_ScreenPullHistoryScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      PullHistoryScreenLoaded( e );
}
}

void ui_event_PullHistoryScreenButtondeletePullHistoryButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
}
}

void ui_event_PullHistoryScreenButtondeletePullHistoryButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      deletePullHistoryButtonClicked( e );
}
}

void ui_event_PullHistoryScreenButtondownloadPullHistoryButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      downloadPullHistoryButtonClicked( e );
      _ui_screen_change( &ui_ScreenExportScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenExportScreen_screen_init);
}
}

// build funtions

void ui_ScreenPullHistoryScreen_screen_init(void)
{
ui_ScreenPullHistoryScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenPullHistoryScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenPullHistoryScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScreenPullHistoryScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_ScreenPullHistoryScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenPullHistoryScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenPullHistoryScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenPullHistoryScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenPanelTablePanel = lv_obj_create(ui_ScreenPullHistoryScreen);
lv_obj_set_width( ui_PullHistoryScreenPanelTablePanel, lv_pct(100));
lv_obj_set_flex_grow( ui_PullHistoryScreenPanelTablePanel, 1);
lv_obj_set_x( ui_PullHistoryScreenPanelTablePanel, -39 );
lv_obj_set_y( ui_PullHistoryScreenPanelTablePanel, -2 );
lv_obj_set_align( ui_PullHistoryScreenPanelTablePanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PullHistoryScreenPanelTablePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PullHistoryScreenPanelTablePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PullHistoryScreenPanelTablePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PullHistoryScreenPanelTablePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PullHistoryScreenPanelTablePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenContainerButtonContainer = lv_obj_create(ui_ScreenPullHistoryScreen);
lv_obj_remove_style_all(ui_PullHistoryScreenContainerButtonContainer);
lv_obj_set_height( ui_PullHistoryScreenContainerButtonContainer, 60);
lv_obj_set_width( ui_PullHistoryScreenContainerButtonContainer, lv_pct(100));
lv_obj_set_x( ui_PullHistoryScreenContainerButtonContainer, 34 );
lv_obj_set_y( ui_PullHistoryScreenContainerButtonContainer, 146 );
lv_obj_set_align( ui_PullHistoryScreenContainerButtonContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PullHistoryScreenContainerButtonContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PullHistoryScreenContainerButtonContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PullHistoryScreenContainerButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PullHistoryScreenButtondeletePullHistoryButton = lv_btn_create(ui_PullHistoryScreenContainerButtonContainer);
lv_obj_set_height( ui_PullHistoryScreenButtondeletePullHistoryButton, 50);
lv_obj_set_width( ui_PullHistoryScreenButtondeletePullHistoryButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_PullHistoryScreenButtondeletePullHistoryButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PullHistoryScreenButtondeletePullHistoryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PullHistoryScreenButtondeletePullHistoryButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondeletePullHistoryButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_indicDisabled);
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondeletePullHistoryButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_indicDisabled);
lv_obj_set_style_text_font(ui_PullHistoryScreenButtondeletePullHistoryButton, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel = lv_label_create(ui_PullHistoryScreenButtondeletePullHistoryButton);
lv_obj_set_width( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel,"Back");
lv_obj_set_style_text_color(ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenButtondeletePullHistoryButton1 = lv_btn_create(ui_PullHistoryScreenContainerButtonContainer);
lv_obj_set_height( ui_PullHistoryScreenButtondeletePullHistoryButton1, 50);
lv_obj_set_width( ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Red);
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondeletePullHistoryButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Red);
lv_obj_set_style_text_font(ui_PullHistoryScreenButtondeletePullHistoryButton1, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1 = lv_label_create(ui_PullHistoryScreenButtondeletePullHistoryButton1);
lv_obj_set_width( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1,"Delete Pull History");

ui_PullHistoryScreenButtondownloadPullHistoryButton = lv_btn_create(ui_PullHistoryScreenContainerButtonContainer);
lv_obj_set_height( ui_PullHistoryScreenButtondownloadPullHistoryButton, 50);
lv_obj_set_width( ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Green);
ui_object_set_themeable_style_property(ui_PullHistoryScreenButtondownloadPullHistoryButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Green);
lv_obj_set_style_text_font(ui_PullHistoryScreenButtondownloadPullHistoryButton, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel = lv_label_create(ui_PullHistoryScreenButtondownloadPullHistoryButton);
lv_obj_set_width( ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel,"Download Pull History");

lv_obj_add_event_cb(ui_PullHistoryScreenButtondeletePullHistoryButton, ui_event_PullHistoryScreenButtondeletePullHistoryButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PullHistoryScreenButtondeletePullHistoryButton1, ui_event_PullHistoryScreenButtondeletePullHistoryButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PullHistoryScreenButtondownloadPullHistoryButton, ui_event_PullHistoryScreenButtondownloadPullHistoryButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenPullHistoryScreen, ui_event_ScreenPullHistoryScreen, LV_EVENT_ALL, NULL);
uic_PullHistoryScreenPanelTablePanel = ui_PullHistoryScreenPanelTablePanel;
uic_PullHistoryScreenContainerButtonContainer = ui_PullHistoryScreenContainerButtonContainer;
uic_PullHistoryScreenButtondeletePullHistoryButton = ui_PullHistoryScreenButtondeletePullHistoryButton;
uic_PullHistoryScreenLabeldeletePullHistoryButtonLabel = ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel;
uic_PullHistoryScreenButtondeletePullHistoryButton1 = ui_PullHistoryScreenButtondeletePullHistoryButton1;
uic_PullHistoryScreenButtondownloadPullHistoryButton = ui_PullHistoryScreenButtondownloadPullHistoryButton;
uic_PullHistoryScreenLabeldownloadPullHistoryButtonLabel = ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel;

}

void ui_ScreenPullHistoryScreen_screen_destroy(void)
{
   if (ui_ScreenPullHistoryScreen) lv_obj_del(ui_ScreenPullHistoryScreen);

// NULL screen variables
ui_ScreenPullHistoryScreen= NULL;
uic_PullHistoryScreenPanelTablePanel= NULL;
ui_PullHistoryScreenPanelTablePanel= NULL;
uic_PullHistoryScreenContainerButtonContainer= NULL;
ui_PullHistoryScreenContainerButtonContainer= NULL;
uic_PullHistoryScreenButtondeletePullHistoryButton= NULL;
ui_PullHistoryScreenButtondeletePullHistoryButton= NULL;
uic_PullHistoryScreenLabeldeletePullHistoryButtonLabel= NULL;
ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel= NULL;
uic_PullHistoryScreenButtondeletePullHistoryButton1= NULL;
ui_PullHistoryScreenButtondeletePullHistoryButton1= NULL;
ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1= NULL;
uic_PullHistoryScreenButtondownloadPullHistoryButton= NULL;
ui_PullHistoryScreenButtondownloadPullHistoryButton= NULL;
uic_PullHistoryScreenLabeldownloadPullHistoryButtonLabel= NULL;
ui_PullHistoryScreenLabeldownloadPullHistoryButtonLabel= NULL;

}
