// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "../ui.h"

void ui_ScreenSettings_screen_init(void)
{
ui_ScreenSettings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsTabviewSettingsView = lv_tabview_create(ui_ScreenSettings, LV_DIR_LEFT, 100);
lv_obj_set_width( ui_SettingsTabviewSettingsView, lv_pct(100));
lv_obj_set_height( ui_SettingsTabviewSettingsView, lv_pct(100));
lv_obj_set_align( ui_SettingsTabviewSettingsView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingsTabviewSettingsView, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsTabpageGeneral = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "General");
lv_obj_set_flex_flow(ui_SettingsTabpageGeneral,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsTabpageGeneral, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsTabpageGeneral, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsPanelGeneralSettings = lv_obj_create(ui_SettingsTabpageGeneral);
lv_obj_set_width( ui_SettingsPanelGeneralSettings, lv_pct(100));
lv_obj_set_height( ui_SettingsPanelGeneralSettings, lv_pct(100));
lv_obj_set_x( ui_SettingsPanelGeneralSettings, -200 );
lv_obj_set_y( ui_SettingsPanelGeneralSettings, -190 );
lv_obj_set_align( ui_SettingsPanelGeneralSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsPanelGeneralSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsPanelGeneralSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsPanelGeneralSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsContainerUnitsSetting = lv_obj_create(ui_SettingsPanelGeneralSettings);
lv_obj_remove_style_all(ui_SettingsContainerUnitsSetting);
lv_obj_set_width( ui_SettingsContainerUnitsSetting, 180);
lv_obj_set_height( ui_SettingsContainerUnitsSetting, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SettingsContainerUnitsSetting, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerUnitsSetting,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainerUnitsSetting, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsContainerUnitsSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelUnitsMetric = lv_label_create(ui_SettingsContainerUnitsSetting);
lv_obj_set_width( ui_SettingsLabelUnitsMetric, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelUnitsMetric, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelUnitsMetric, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelUnitsMetric,"Metric");

ui_SettingsSwitchUnits = lv_switch_create(ui_SettingsContainerUnitsSetting);
lv_obj_set_width( ui_SettingsSwitchUnits, 50);
lv_obj_set_height( ui_SettingsSwitchUnits, 25);
lv_obj_set_align( ui_SettingsSwitchUnits, LV_ALIGN_CENTER );
lv_obj_add_state( ui_SettingsSwitchUnits, LV_STATE_CHECKED );     /// States
lv_obj_set_style_bg_color(ui_SettingsSwitchUnits, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SettingsSwitchUnits, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_SettingsSwitchUnits, lv_color_hex(0xE6E2E6), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SettingsSwitchUnits, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_SettingsLabelUnitsImperial = lv_label_create(ui_SettingsContainerUnitsSetting);
lv_obj_set_width( ui_SettingsLabelUnitsImperial, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelUnitsImperial, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelUnitsImperial, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelUnitsImperial,"Imperial");

ui_SettingsContainerBenchmarkSetting = lv_obj_create(ui_SettingsPanelGeneralSettings);
lv_obj_remove_style_all(ui_SettingsContainerBenchmarkSetting);
lv_obj_set_width( ui_SettingsContainerBenchmarkSetting, 248);
lv_obj_set_height( ui_SettingsContainerBenchmarkSetting, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SettingsContainerBenchmarkSetting, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerBenchmarkSetting,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainerBenchmarkSetting, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsContainerBenchmarkSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsSwitchBenchmark = lv_switch_create(ui_SettingsContainerBenchmarkSetting);
lv_obj_set_width( ui_SettingsSwitchBenchmark, 50);
lv_obj_set_height( ui_SettingsSwitchBenchmark, 25);
lv_obj_set_align( ui_SettingsSwitchBenchmark, LV_ALIGN_CENTER );

ui_SettingsLabelBenchmarkTitle = lv_label_create(ui_SettingsContainerBenchmarkSetting);
lv_obj_set_width( ui_SettingsLabelBenchmarkTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelBenchmarkTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelBenchmarkTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBenchmarkTitle,"Display Benchmark Data");

ui_SettingsContainerBrightnessSetting = lv_obj_create(ui_SettingsPanelGeneralSettings);
lv_obj_remove_style_all(ui_SettingsContainerBrightnessSetting);
lv_obj_set_width( ui_SettingsContainerBrightnessSetting, 547);
lv_obj_set_height( ui_SettingsContainerBrightnessSetting, 25);
lv_obj_set_align( ui_SettingsContainerBrightnessSetting, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerBrightnessSetting,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainerBrightnessSetting, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainerBrightnessSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelBrightnessTitle = lv_label_create(ui_SettingsContainerBrightnessSetting);
lv_obj_set_width( ui_SettingsLabelBrightnessTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelBrightnessTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelBrightnessTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBrightnessTitle,"Brightness");

ui_SettingsSliderSlider1 = lv_slider_create(ui_SettingsContainerBrightnessSetting);
lv_slider_set_range(ui_SettingsSliderSlider1, 1,255);
lv_slider_set_value( ui_SettingsSliderSlider1, 128, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SettingsSliderSlider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SettingsSliderSlider1, 255, LV_ANIM_OFF);
lv_obj_set_width( ui_SettingsSliderSlider1, 369);
lv_obj_set_height( ui_SettingsSliderSlider1, 10);
lv_obj_set_align( ui_SettingsSliderSlider1, LV_ALIGN_CENTER );

ui_SettingsLabelBrightness = lv_label_create(ui_SettingsContainerBrightnessSetting);
lv_obj_set_width( ui_SettingsLabelBrightness, lv_pct(10));
lv_obj_set_height( ui_SettingsLabelBrightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelBrightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBrightness,"50%");

ui_SettingsTabpageSpeed_and_Distance = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Speed + Distance");
lv_obj_clear_flag( ui_SettingsTabpageSpeed_and_Distance, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsTabpageTach = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Tach");
lv_obj_clear_flag( ui_SettingsTabpageTach, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsTabpageRelays_and_Limits = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Relays + Limits");
lv_obj_set_flex_flow(ui_SettingsTabpageRelays_and_Limits,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsTabpageRelays_and_Limits, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_row(ui_SettingsTabpageRelays_and_Limits, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsTabpageRelays_and_Limits, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsPanelConnectionRLM = lv_obj_create(ui_SettingsTabpageRelays_and_Limits);
lv_obj_set_width( ui_SettingsPanelConnectionRLM, lv_pct(100));
lv_obj_set_height( ui_SettingsPanelConnectionRLM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsPanelConnectionRLM, -118 );
lv_obj_set_y( ui_SettingsPanelConnectionRLM, -111 );
lv_obj_set_align( ui_SettingsPanelConnectionRLM, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsPanelConnectionRLM,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsPanelConnectionRLM, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsPanelConnectionRLM, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsContainerContainer8 = lv_obj_create(ui_SettingsPanelConnectionRLM);
lv_obj_remove_style_all(ui_SettingsContainerContainer8);
lv_obj_set_height( ui_SettingsContainerContainer8, 50);
lv_obj_set_width( ui_SettingsContainerContainer8, lv_pct(100));
lv_obj_set_align( ui_SettingsContainerContainer8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerContainer8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainerContainer8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainerContainer8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainerContainer8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainerContainer8, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsContainerContainer9 = lv_obj_create(ui_SettingsContainerContainer8);
lv_obj_remove_style_all(ui_SettingsContainerContainer9);
lv_obj_set_height( ui_SettingsContainerContainer9, 50);
lv_obj_set_flex_grow( ui_SettingsContainerContainer9, 1);
lv_obj_set_align( ui_SettingsContainerContainer9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerContainer9,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainerContainer9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainerContainer9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainerContainer9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainerContainer9, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsButtonButton1 = lv_btn_create(ui_SettingsContainerContainer9);
lv_obj_set_height( ui_SettingsButtonButton1, 50);
lv_obj_set_width( ui_SettingsButtonButton1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_SettingsButtonButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsButtonButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButtonButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelLabel6 = lv_label_create(ui_SettingsButtonButton1);
lv_obj_set_width( ui_SettingsLabelLabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel6,"Connect to Relay and Limit Module");

ui_SettingsLabelLabel7 = lv_label_create(ui_SettingsContainerContainer9);
lv_obj_set_width( ui_SettingsLabelLabel7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel7, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel7,"No Connection");

ui_SettingsPanelRelayLimitSettings = lv_obj_create(ui_SettingsTabpageRelays_and_Limits);
lv_obj_set_width( ui_SettingsPanelRelayLimitSettings, lv_pct(100));
lv_obj_set_height( ui_SettingsPanelRelayLimitSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsPanelRelayLimitSettings, -118 );
lv_obj_set_y( ui_SettingsPanelRelayLimitSettings, -111 );
lv_obj_set_align( ui_SettingsPanelRelayLimitSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsPanelRelayLimitSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsPanelRelayLimitSettings, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsPanelRelayLimitSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsPanelRelayLimitSettings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsContainerRelaySettings = lv_obj_create(ui_SettingsPanelRelayLimitSettings);
lv_obj_remove_style_all(ui_SettingsContainerRelaySettings);
lv_obj_set_width( ui_SettingsContainerRelaySettings, 607);
lv_obj_set_height( ui_SettingsContainerRelaySettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsContainerRelaySettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerRelaySettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsContainerRelaySettings, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainerRelaySettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainerRelaySettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainerRelaySettings, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsLabellblRelays = lv_label_create(ui_SettingsContainerRelaySettings);
lv_obj_set_width( ui_SettingsLabellblRelays, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabellblRelays, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabellblRelays, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabellblRelays,"Relays");
lv_obj_set_style_text_font(ui_SettingsLabellblRelays, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsContainercontainerEnableRelay = lv_obj_create(ui_SettingsContainerRelaySettings);
lv_obj_remove_style_all(ui_SettingsContainercontainerEnableRelay);
lv_obj_set_width( ui_SettingsContainercontainerEnableRelay, lv_pct(100));
lv_obj_set_height( ui_SettingsContainercontainerEnableRelay, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SettingsContainercontainerEnableRelay, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainerEnableRelay,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainerEnableRelay, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( ui_SettingsContainercontainerEnableRelay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainercontainerEnableRelay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainercontainerEnableRelay, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsSwitchSwitch1 = lv_switch_create(ui_SettingsContainercontainerEnableRelay);
lv_obj_set_width( ui_SettingsSwitchSwitch1, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch1, 25);
lv_obj_set_x( ui_SettingsSwitchSwitch1, 65 );
lv_obj_set_y( ui_SettingsSwitchSwitch1, 0 );
lv_obj_set_align( ui_SettingsSwitchSwitch1, LV_ALIGN_CENTER );

ui_SettingsLabelLabel1 = lv_label_create(ui_SettingsContainercontainerEnableRelay);
lv_obj_set_width( ui_SettingsLabelLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel1,"Enable Relay Feature");

ui_SettingsContainerrealayversion1 = lv_obj_create(ui_SettingsContainerRelaySettings);
lv_obj_remove_style_all(ui_SettingsContainerrealayversion1);
lv_obj_set_width( ui_SettingsContainerrealayversion1, lv_pct(98));
lv_obj_set_height( ui_SettingsContainerrealayversion1, LV_SIZE_CONTENT);   /// 374
lv_obj_set_align( ui_SettingsContainerrealayversion1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainerrealayversion1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_SettingsContainerrealayversion1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsContainerrealayversion1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsContainercontainterRelaySwitch1 = lv_obj_create(ui_SettingsContainerrealayversion1);
lv_obj_remove_style_all(ui_SettingsContainercontainterRelaySwitch1);
lv_obj_set_height( ui_SettingsContainercontainterRelaySwitch1, 50);
lv_obj_set_width( ui_SettingsContainercontainterRelaySwitch1, lv_pct(100));
lv_obj_set_align( ui_SettingsContainercontainterRelaySwitch1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainterRelaySwitch1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainterRelaySwitch1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_SettingsContainercontainterRelaySwitch1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelLabel21 = lv_label_create(ui_SettingsContainercontainterRelaySwitch1);
lv_obj_set_width( ui_SettingsLabelLabel21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel21, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel21,"R1");

ui_SettingsSwitchSwitch3 = lv_switch_create(ui_SettingsContainercontainterRelaySwitch1);
lv_obj_set_width( ui_SettingsSwitchSwitch3, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch3, 25);
lv_obj_set_align( ui_SettingsSwitchSwitch3, LV_ALIGN_CENTER );

ui_SettingsDropdownDropdown1 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch1);
lv_dropdown_set_options( ui_SettingsDropdownDropdown1, "Distance Alarm 1\nDistance Alarm 2\nMPH Alarm\nTach Alarm\nLimit Switch 1\nLimit Switch 2\nPull State: READY\nPull State: STAGED\nPull State: IN PULL" );
lv_obj_set_width( ui_SettingsDropdownDropdown1, lv_pct(34));
lv_obj_set_height( ui_SettingsDropdownDropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsDropdownDropdown2 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch1);
lv_dropdown_set_options( ui_SettingsDropdownDropdown2, "Make\nBreak\nWhen Entered\nWhen Exited" );
lv_obj_set_width( ui_SettingsDropdownDropdown2, lv_pct(38));
lv_obj_set_height( ui_SettingsDropdownDropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsContainercontainterRelaySwitch2 = lv_obj_create(ui_SettingsContainerrealayversion1);
lv_obj_remove_style_all(ui_SettingsContainercontainterRelaySwitch2);
lv_obj_set_height( ui_SettingsContainercontainterRelaySwitch2, 50);
lv_obj_set_width( ui_SettingsContainercontainterRelaySwitch2, lv_pct(100));
lv_obj_set_align( ui_SettingsContainercontainterRelaySwitch2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainterRelaySwitch2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainterRelaySwitch2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_SettingsContainercontainterRelaySwitch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelLabel5 = lv_label_create(ui_SettingsContainercontainterRelaySwitch2);
lv_obj_set_width( ui_SettingsLabelLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel5,"R2");

ui_SettingsSwitchSwitch2 = lv_switch_create(ui_SettingsContainercontainterRelaySwitch2);
lv_obj_set_width( ui_SettingsSwitchSwitch2, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch2, 25);
lv_obj_set_align( ui_SettingsSwitchSwitch2, LV_ALIGN_CENTER );

ui_SettingsDropdownDropdown3 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch2);
lv_dropdown_set_options( ui_SettingsDropdownDropdown3, "Distance Alarm 1\nDistance Alarm 2\nMPH Alarm\nTach Alarm\nLimit Switch 1\nLimit Switch 2\nPull State: READY\nPull State: STAGED\nPull State: IN PULL" );
lv_obj_set_width( ui_SettingsDropdownDropdown3, lv_pct(34));
lv_obj_set_height( ui_SettingsDropdownDropdown3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsDropdownDropdown4 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch2);
lv_dropdown_set_options( ui_SettingsDropdownDropdown4, "Make\nBreak\nWhen Entered\nWhen Exited" );
lv_obj_set_width( ui_SettingsDropdownDropdown4, lv_pct(38));
lv_obj_set_height( ui_SettingsDropdownDropdown4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsContainercontainterRelaySwitch3 = lv_obj_create(ui_SettingsContainerrealayversion1);
lv_obj_remove_style_all(ui_SettingsContainercontainterRelaySwitch3);
lv_obj_set_height( ui_SettingsContainercontainterRelaySwitch3, 50);
lv_obj_set_width( ui_SettingsContainercontainterRelaySwitch3, lv_pct(100));
lv_obj_set_align( ui_SettingsContainercontainterRelaySwitch3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainterRelaySwitch3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainterRelaySwitch3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_SettingsContainercontainterRelaySwitch3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelLabel8 = lv_label_create(ui_SettingsContainercontainterRelaySwitch3);
lv_obj_set_width( ui_SettingsLabelLabel8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel8, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel8,"R2");

ui_SettingsSwitchSwitch5 = lv_switch_create(ui_SettingsContainercontainterRelaySwitch3);
lv_obj_set_width( ui_SettingsSwitchSwitch5, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch5, 25);
lv_obj_set_align( ui_SettingsSwitchSwitch5, LV_ALIGN_CENTER );

ui_SettingsDropdownDropdown5 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch3);
lv_dropdown_set_options( ui_SettingsDropdownDropdown5, "Distance Alarm 1\nDistance Alarm 2\nMPH Alarm\nTach Alarm\nLimit Switch 1\nLimit Switch 2\nPull State: READY\nPull State: STAGED\nPull State: IN PULL" );
lv_obj_set_width( ui_SettingsDropdownDropdown5, lv_pct(34));
lv_obj_set_height( ui_SettingsDropdownDropdown5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsDropdownDropdown6 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch3);
lv_dropdown_set_options( ui_SettingsDropdownDropdown6, "Make\nBreak\nWhen Entered\nWhen Exited" );
lv_obj_set_width( ui_SettingsDropdownDropdown6, lv_pct(38));
lv_obj_set_height( ui_SettingsDropdownDropdown6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsContainercontainterRelaySwitch4 = lv_obj_create(ui_SettingsContainerrealayversion1);
lv_obj_remove_style_all(ui_SettingsContainercontainterRelaySwitch4);
lv_obj_set_height( ui_SettingsContainercontainterRelaySwitch4, 50);
lv_obj_set_width( ui_SettingsContainercontainterRelaySwitch4, lv_pct(100));
lv_obj_set_align( ui_SettingsContainercontainterRelaySwitch4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainterRelaySwitch4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainterRelaySwitch4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_SettingsContainercontainterRelaySwitch4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelLabel9 = lv_label_create(ui_SettingsContainercontainterRelaySwitch4);
lv_obj_set_width( ui_SettingsLabelLabel9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel9, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel9,"R2");

ui_SettingsSwitchSwitch6 = lv_switch_create(ui_SettingsContainercontainterRelaySwitch4);
lv_obj_set_width( ui_SettingsSwitchSwitch6, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch6, 25);
lv_obj_set_align( ui_SettingsSwitchSwitch6, LV_ALIGN_CENTER );

ui_SettingsDropdownDropdown7 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch4);
lv_dropdown_set_options( ui_SettingsDropdownDropdown7, "Distance Alarm 1\nDistance Alarm 2\nMPH Alarm\nTach Alarm\nLimit Switch 1\nLimit Switch 2\nPull State: READY\nPull State: STAGED\nPull State: IN PULL" );
lv_obj_set_width( ui_SettingsDropdownDropdown7, lv_pct(34));
lv_obj_set_height( ui_SettingsDropdownDropdown7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsDropdownDropdown8 = lv_dropdown_create(ui_SettingsContainercontainterRelaySwitch4);
lv_dropdown_set_options( ui_SettingsDropdownDropdown8, "Make\nBreak\nWhen Entered\nWhen Exited" );
lv_obj_set_width( ui_SettingsDropdownDropdown8, lv_pct(38));
lv_obj_set_height( ui_SettingsDropdownDropdown8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDropdownDropdown8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDropdownDropdown8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_SettingsContainercontainerLimitSettings = lv_obj_create(ui_SettingsPanelRelayLimitSettings);
lv_obj_remove_style_all(ui_SettingsContainercontainerLimitSettings);
lv_obj_set_width( ui_SettingsContainercontainerLimitSettings, 303);
lv_obj_set_height( ui_SettingsContainercontainerLimitSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsContainercontainerLimitSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainerLimitSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsContainercontainerLimitSettings, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainercontainerLimitSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainercontainerLimitSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainercontainerLimitSettings, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsLabelLabel2 = lv_label_create(ui_SettingsContainercontainerLimitSettings);
lv_obj_set_width( ui_SettingsLabelLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelLabel2,"Limit Switches");
lv_obj_set_style_text_font(ui_SettingsLabelLabel2, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsContainercontainerEnableLimit = lv_obj_create(ui_SettingsContainercontainerLimitSettings);
lv_obj_remove_style_all(ui_SettingsContainercontainerEnableLimit);
lv_obj_set_height( ui_SettingsContainercontainerEnableLimit, 50);
lv_obj_set_width( ui_SettingsContainercontainerEnableLimit, lv_pct(100));
lv_obj_set_align( ui_SettingsContainercontainerEnableLimit, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsContainercontainerEnableLimit,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SettingsContainercontainerEnableLimit, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsContainercontainerEnableLimit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsContainercontainerEnableLimit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsContainercontainerEnableLimit, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsSwitchSwitch4 = lv_switch_create(ui_SettingsContainercontainerEnableLimit);
lv_obj_set_width( ui_SettingsSwitchSwitch4, 50);
lv_obj_set_height( ui_SettingsSwitchSwitch4, 25);
lv_obj_set_x( ui_SettingsSwitchSwitch4, 65 );
lv_obj_set_y( ui_SettingsSwitchSwitch4, 0 );
lv_obj_set_align( ui_SettingsSwitchSwitch4, LV_ALIGN_CENTER );

ui_SettingsLabelLabel3 = lv_label_create(ui_SettingsContainercontainerEnableLimit);
lv_obj_set_width( ui_SettingsLabelLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelLabel3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_SettingsLabelLabel3,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_SettingsLabelLabel3,"Enable Limit Switch Feature");

ui_SettingsPanelPanel1 = lv_obj_create(ui_SettingsContainercontainerLimitSettings);
lv_obj_set_height( ui_SettingsPanelPanel1, 50);
lv_obj_set_width( ui_SettingsPanelPanel1, lv_pct(100));
lv_obj_set_align( ui_SettingsPanelPanel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingsPanelPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsTabpageJudge = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Judge");
lv_obj_clear_flag( ui_SettingsTabpageJudge, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsTabpageSafety_and_Displays = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Safety + Displays");
lv_obj_clear_flag( ui_SettingsTabpageSafety_and_Displays, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsTabpageAbout = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "About");
lv_obj_clear_flag( ui_SettingsTabpageAbout, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsPanelAboutInfo = lv_obj_create(ui_SettingsTabpageAbout);
lv_obj_set_width( ui_SettingsPanelAboutInfo, lv_pct(100));
lv_obj_set_height( ui_SettingsPanelAboutInfo, lv_pct(100));
lv_obj_set_align( ui_SettingsPanelAboutInfo, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsPanelAboutInfo,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_SettingsPanelAboutInfo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsPanelAboutInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelAboutTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelAboutTitle, lv_pct(100));
lv_obj_set_height( ui_SettingsLabelAboutTitle, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_SettingsLabelAboutTitle,"M4 Sled Monitor");
lv_obj_set_style_text_font(ui_SettingsLabelAboutTitle, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsLabelVersionTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelVersionTitle, lv_pct(24));
lv_obj_set_height( ui_SettingsLabelVersionTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelVersionTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelVersionTitle,"Version:");

ui_SettingsLabelVersionData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelVersionData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelVersionData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelVersionData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelVersionData,"0.0.1");

ui_SettingsLabelBuildDateTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelBuildDateTitle, lv_pct(24));
lv_obj_set_height( ui_SettingsLabelBuildDateTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelBuildDateTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBuildDateTitle,"Build Date:");

ui_SettingsLabelBuildDateData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelBuildDateData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelBuildDateData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelBuildDateData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBuildDateData,"April 2025");

ui_SettingsLabelDevelopedByTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelDevelopedByTitle, lv_pct(24));
lv_obj_set_height( ui_SettingsLabelDevelopedByTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelDevelopedByTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelDevelopedByTitle,"Developed by:");

ui_SettingsLabelDevelopedByData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelDevelopedByData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelDevelopedByData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelDevelopedByData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelDevelopedByData,"Agri-Tronix Corporation\nFranklin, Indiana, USA\nwww.agritronix.com");

ui_SettingsLabelInfoTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelInfoTitle, lv_pct(24));
lv_obj_set_height( ui_SettingsLabelInfoTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelInfoTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelInfoTitle,"Info:");

ui_SettingsLabelInfoData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelInfoData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelInfoData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelInfoData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelInfoData,"This software monitors sled distance, speed, tach, pull status, and alarm conditions in real time.\nRelays and outputs can be triggered based on customizable logic.");

ui_SettingsLabelSupportTitle = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelSupportTitle, lv_pct(24));
lv_obj_set_height( ui_SettingsLabelSupportTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelSupportTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelSupportTitle,"Support:");

ui_SettingsLabelSupportData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelSupportData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelSupportData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelSupportData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelSupportData,"support@agritronix.com\n(317) 738-4474");

ui_SettingsLabelCopyrightData = lv_label_create(ui_SettingsPanelAboutInfo);
lv_obj_set_width( ui_SettingsLabelCopyrightData, lv_pct(73));
lv_obj_set_height( ui_SettingsLabelCopyrightData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelCopyrightData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelCopyrightData,"(c) Agri-Tronix Corporation");

ui_SettingsTabpageExit = lv_tabview_add_tab(ui_SettingsTabviewSettingsView, "Exit");
lv_obj_clear_flag( ui_SettingsTabpageExit, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_SettingsLabelBountyMessage = lv_label_create(ui_SettingsTabpageExit);
lv_obj_set_width( ui_SettingsLabelBountyMessage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelBountyMessage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsLabelBountyMessage, -7 );
lv_obj_set_y( ui_SettingsLabelBountyMessage, -69 );
lv_obj_set_align( ui_SettingsLabelBountyMessage, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelBountyMessage,"Oh, Hi!\nHow did you get here?  This page shouldn't even exist.\n\nBut hey I guess since you found you're way here, you found a bug!!\n\nGreat for you, not so great for me, the guy writing all this code.  but...\nI'll tell you what, if you are the first person to give me reproducable steps\non how you found yourself here, I'll send you a $10 Amazon gift card!\n\nCool Beans! See ya later!\n\n-Adam");

ui_SettingsButtonReturnHome = lv_btn_create(ui_SettingsTabpageExit);
lv_obj_set_height( ui_SettingsButtonReturnHome, 50);
lv_obj_set_width( ui_SettingsButtonReturnHome, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_SettingsButtonReturnHome, -4 );
lv_obj_set_y( ui_SettingsButtonReturnHome, 85 );
lv_obj_set_align( ui_SettingsButtonReturnHome, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsButtonReturnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButtonReturnHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsLabelButtonReturnHome = lv_label_create(ui_SettingsButtonReturnHome);
lv_obj_set_width( ui_SettingsLabelButtonReturnHome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabelButtonReturnHome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsLabelButtonReturnHome, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabelButtonReturnHome,"Return To home");

ui_SettingsContainerExitButtonOverlay = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_SettingsContainerExitButtonOverlay);
lv_obj_set_width( ui_SettingsContainerExitButtonOverlay, 100);
lv_obj_set_height( ui_SettingsContainerExitButtonOverlay, 50);
lv_obj_set_align( ui_SettingsContainerExitButtonOverlay, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_SettingsContainerExitButtonOverlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_SettingsSwitchUnits, ui_event_SettingsSwitchUnits, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsSwitchBenchmark, ui_event_SettingsSwitchBenchmark, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsSliderSlider1, ui_event_SettingsSliderSlider1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsButtonReturnHome, ui_event_SettingsButtonReturnHome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsTabpageExit, ui_event_SettingsTabpageExit, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsContainerExitButtonOverlay, ui_event_SettingsContainerExitButtonOverlay, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenSettings, ui_event_ScreenSettings, LV_EVENT_ALL, NULL);
uic_ScreenSettings = ui_ScreenSettings;
uic_SettingsTabviewSettingsView = ui_SettingsTabviewSettingsView;
uic_SettingsPanelGeneralSettings = ui_SettingsPanelGeneralSettings;
uic_SettingsContainerUnitsSetting = ui_SettingsContainerUnitsSetting;
uic_SettingsLabelUnitsMetric = ui_SettingsLabelUnitsMetric;
uic_SettingsSwitchUnits = ui_SettingsSwitchUnits;
uic_SettingsLabelUnitsImperial = ui_SettingsLabelUnitsImperial;
uic_SettingsContainerBenchmarkSetting = ui_SettingsContainerBenchmarkSetting;
uic_SettingsSwitchBenchmark = ui_SettingsSwitchBenchmark;
uic_SettingsLabelBenchmarkTitle = ui_SettingsLabelBenchmarkTitle;
uic_SettingsContainerBrightnessSetting = ui_SettingsContainerBrightnessSetting;
uic_SettingsLabelBrightnessTitle = ui_SettingsLabelBrightnessTitle;
uic_SettingsLabelBrightness = ui_SettingsLabelBrightness;
uic_SettingsPanelConnectionRLM = ui_SettingsPanelConnectionRLM;
uic_SettingsPanelRelayLimitSettings = ui_SettingsPanelRelayLimitSettings;
uic_SettingsContainerRelaySettings = ui_SettingsContainerRelaySettings;
uic_SettingsLabellblRelays = ui_SettingsLabellblRelays;
uic_SettingsContainercontainerEnableRelay = ui_SettingsContainercontainerEnableRelay;
uic_SettingsContainercontainterRelaySwitch1 = ui_SettingsContainercontainterRelaySwitch1;
uic_SettingsContainercontainerLimitSettings = ui_SettingsContainercontainerLimitSettings;
uic_SettingsContainercontainerEnableLimit = ui_SettingsContainercontainerEnableLimit;
uic_SettingsPanelAboutInfo = ui_SettingsPanelAboutInfo;
uic_SettingsLabelAboutTitle = ui_SettingsLabelAboutTitle;
uic_SettingsLabelVersionTitle = ui_SettingsLabelVersionTitle;
uic_SettingsLabelVersionData = ui_SettingsLabelVersionData;
uic_SettingsLabelBuildDateTitle = ui_SettingsLabelBuildDateTitle;
uic_SettingsLabelBuildDateData = ui_SettingsLabelBuildDateData;
uic_SettingsLabelDevelopedByTitle = ui_SettingsLabelDevelopedByTitle;
uic_SettingsLabelDevelopedByData = ui_SettingsLabelDevelopedByData;
uic_SettingsLabelInfoTitle = ui_SettingsLabelInfoTitle;
uic_SettingsLabelInfoData = ui_SettingsLabelInfoData;
uic_SettingsLabelSupportData = ui_SettingsLabelSupportData;
uic_SettingsLabelCopyrightData = ui_SettingsLabelCopyrightData;
uic_SettingsLabelBountyMessage = ui_SettingsLabelBountyMessage;
uic_SettingsButtonReturnHome = ui_SettingsButtonReturnHome;
uic_SettingsLabelButtonReturnHome = ui_SettingsLabelButtonReturnHome;
uic_SettingsContainerExitButtonOverlay = ui_SettingsContainerExitButtonOverlay;

}
