// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern void ui_event_ScreenMain( lv_event_t * e);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_MainContainerMainContainer;
extern lv_obj_t *ui_MainContainerTop;
extern lv_obj_t *ui_MainContainerHeader;
extern lv_obj_t *ui_MainContainerClass;
extern lv_obj_t *ui_MainContainerClassNameLabel;
extern lv_obj_t *ui_MainLabelClassName;
extern void ui_event_MainContainerSettingsButton( lv_event_t * e);
extern lv_obj_t *ui_MainContainerSettingsButton;
extern void ui_event_MainButtonSettings( lv_event_t * e);
extern lv_obj_t *ui_MainButtonSettings;
extern void ui_event_MainContainerM4IDNumberContainer( lv_event_t * e);
extern lv_obj_t *ui_MainContainerM4IDNumberContainer;
extern lv_obj_t *ui_MainLabelM4IDNumberLabel;
extern void ui_event_MainContainerAlarmPresetContainer( lv_event_t * e);
extern lv_obj_t *ui_MainContainerAlarmPresetContainer;
extern lv_obj_t *ui_MainLabelAlarmPresetLable;
extern lv_obj_t *ui_MainContainerDriver;
extern void ui_event_MainButtonButton6( lv_event_t * e);
extern lv_obj_t *ui_MainButtonButton6;
extern lv_obj_t *ui_MainContainerDriverTitleLabel;
extern lv_obj_t *ui_MainLabelDriverTitle;
extern lv_obj_t *ui_MainLabelDriverNumber;
extern lv_obj_t *ui_MainContainerDriverNameLabel;
extern lv_obj_t *ui_MainLabelDriverName;
extern lv_obj_t *ui_MainContainerDriverChangeButton;
extern void ui_event_MainButtonDriverChange( lv_event_t * e);
extern lv_obj_t *ui_MainButtonDriverChange;
extern lv_obj_t *ui_MainContainerDistance;
extern lv_obj_t *ui_MainLabelDistanceValue;
extern lv_obj_t *ui_MainLabelDistanceUnit;
extern lv_obj_t *ui_MainContainerMid;
extern lv_obj_t *ui_MainContainerTach;
extern lv_obj_t *ui_MainContainerTachTitleLabel;
extern lv_obj_t *ui_MainContainerTachTitleSpacer;
extern lv_obj_t *ui_MainLabelTachTitle;
extern lv_obj_t *ui_MainContainertachTractorConnectedIconContainer;
extern lv_obj_t *ui_MainImagetachConn;
extern lv_obj_t *ui_MainImagetachConnNo;
extern lv_obj_t *ui_MainContainerTachData;
extern lv_obj_t *ui_MainContainerTachAlarmIndicator;
extern lv_obj_t *ui_MainPanelMainPanelTachAlarmIndicatorIcon2;
extern lv_obj_t *ui_MainPanelTachAlarmIndicatorIcon1;
extern lv_obj_t *ui_MainLabelTachValue;
extern lv_obj_t *ui_MainLabelTachUnit;
extern lv_obj_t *ui_MainContainerSpeed;
extern lv_obj_t *ui_MainContainerSpeedTitleLabel;
extern lv_obj_t *ui_MainLabelSpeedTitle;
extern lv_obj_t *ui_MainContainerSpeedData;
extern lv_obj_t *ui_MainContainerSpeedAlarmIndicator;
extern lv_obj_t *ui_MainPanelSpeedAlarmIndicatorIcon1;
extern lv_obj_t *ui_MainPanelSpeedAlarmIndicatorIcon2;
extern lv_obj_t *ui_MainLabelSpeedValue;
extern lv_obj_t *ui_MainLabelSpeedUnit;
extern lv_obj_t *ui_MainContainerBottom;
extern lv_obj_t *ui_MainContainerLimit;
extern lv_obj_t *ui_MainContainerLimitTitleLabel;
extern lv_obj_t *ui_MainLabelLimitTitle;
extern lv_obj_t *ui_MainContainerLimitData;
extern lv_obj_t *ui_MainContainerLimitIndicators1;
extern lv_obj_t *ui_MainLabelLimitIndicator1;
extern lv_obj_t *ui_MainPanelLimitIndicatorIcon1;
extern lv_obj_t *ui_MainContainerLimitIndicators2;
extern lv_obj_t *ui_MainLabelLimitIndicator2;
extern lv_obj_t *ui_MainPanelLimitIndicatorIcon2;
extern lv_obj_t *ui_MainContainerPullStateControls;
extern lv_obj_t *ui_MainContainerStateREADY;
extern void ui_event_MainButtonREADYStage( lv_event_t * e);
extern lv_obj_t *ui_MainButtonREADYStage;
extern lv_obj_t *ui_MainLabelButtonStage;
extern lv_obj_t *ui_MainContainerStateSTAGED;
extern void ui_event_MainButtonSTAGEDCancel( lv_event_t * e);
extern lv_obj_t *ui_MainButtonSTAGEDCancel;
extern lv_obj_t *ui_MainLabelButtonStaged;
extern lv_obj_t *ui_MainLabelButtonStagedCancel;
extern lv_obj_t *ui_MainContainerStatePULLING;
extern void ui_event_MainButtonPULLINGStop( lv_event_t * e);
extern lv_obj_t *ui_MainButtonPULLINGStop;
extern lv_obj_t *ui_MainLabelButtonStop;
extern lv_obj_t *ui_MainContainerStatePULLEND;
extern void ui_event_MainButtonPULLENDDiscard( lv_event_t * e);
extern lv_obj_t *ui_MainButtonPULLENDDiscard;
extern lv_obj_t *ui_MainLabelButtonStage1;
extern void ui_event_MainButtonPULLENDSave( lv_event_t * e);
extern lv_obj_t *ui_MainButtonPULLENDSave;
extern lv_obj_t *ui_MainLabelButtonStaged2;
extern void ui_event_MainContainerStateEMERGENCYSTOP( lv_event_t * e);
extern lv_obj_t *ui_MainContainerStateEMERGENCYSTOP;
extern lv_obj_t *ui_MainButtonPULLINGStop1;
extern lv_obj_t *ui_MainLabelButtonStop1;
extern lv_obj_t *ui_MainContainerRelays;
extern lv_obj_t *ui_MainContainerRelaysTitleLabel;
extern lv_obj_t *ui_MainLabelRelaysTitle;
extern lv_obj_t *ui_MainContainerRelaysData;
extern lv_obj_t *ui_MainContainerRelayIndicators1;
extern lv_obj_t *ui_MainLabelRelayIndicator1;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon1;
extern lv_obj_t *ui_MainContainerRelayIndicators2;
extern lv_obj_t *ui_MainLabelRelayIndicator2;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon2;
extern lv_obj_t *ui_MainContainerRelayIndicators3;
extern lv_obj_t *ui_MainLabelRelayIndicator3;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon3;
extern lv_obj_t *ui_MainContainerRelayIndicators4;
extern lv_obj_t *ui_MainLabelRelayIndicator4;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon4;
extern lv_obj_t *ui_MainContainerDistanceProgression;
extern lv_obj_t *ui_MainContainerRaceFlag;
extern lv_obj_t *ui_MainPanelwhite;
extern lv_obj_t *ui_MainPanelblack;
extern lv_obj_t *ui_MainPanelwhite1;
extern lv_obj_t *ui_MainPanelblack1;
extern lv_obj_t *ui_MainPanelwhite2;
extern lv_obj_t *ui_MainPanelblack2;
extern lv_obj_t *ui_MainPanelwhite3;
extern lv_obj_t *ui_MainPanelblack3;
extern lv_obj_t *ui_MainPanelwhite4;
extern lv_obj_t *ui_MainPanelblack4;
extern lv_obj_t *ui_MainPanelwhite5;
extern lv_obj_t *ui_MainPanelblack5;
extern lv_obj_t *ui_MainPanelwhite6;
extern lv_obj_t *ui_MainPanelblack6;
extern lv_obj_t *ui_MainPanelwhite7;
extern lv_obj_t *ui_MainPanelblack7;
extern lv_obj_t *ui_MainPanelwhite8;
extern lv_obj_t *ui_MainPanelblack8;
extern lv_obj_t *ui_MainPanelwhite9;
extern lv_obj_t *ui_MainPanelblack9;
extern lv_obj_t *ui_MainPanelwhite10;
extern lv_obj_t *ui_MainPanelblack10;
extern lv_obj_t *ui_MainContainerDistanceProgressBar;
extern lv_obj_t *ui_MainBarDistanceProgress;
extern lv_obj_t *ui_MainBarDistanceAlarm1;
extern lv_obj_t *ui_MainBarDistanceAlarm2;
extern lv_obj_t *ui_MainContainerDistanceTitleLabel;
extern lv_obj_t *ui_MainLabelDistanceTitle;
extern lv_obj_t *ui_MainLabelDistanceAlarmTriangle1;
extern lv_obj_t *ui_MainLabelDistanceAlarmTriangle2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenMain;
extern lv_obj_t *uic_MainLabelClassName;
extern lv_obj_t *uic_MainButtonSettings;
extern lv_obj_t *uic_MainContainerM4UnitIDContainer;
extern lv_obj_t *uic_MainLabelM4UnitIDLabel;
extern lv_obj_t *uic_MainContainerAlarmPresetContainer;
extern lv_obj_t *uic_MainLabelAlarmPresetLable;
extern lv_obj_t *uic_MainLabelDriverNumber;
extern lv_obj_t *uic_MainLabelDriverName;
extern lv_obj_t *uic_MainButtonDriverChange;
extern lv_obj_t *uic_MainLabelDistanceValue;
extern lv_obj_t *uic_MainLabelDistanceUnit;
extern lv_obj_t *uic_MainContainerTach;
extern lv_obj_t *uic_MainContainerTachTitleSpacer;
extern lv_obj_t *uic_MainLabelTachTitle;
extern lv_obj_t *uic_MainContainertachTractorConnectedIconContainer;
extern lv_obj_t *uic_MainImagetachConn;
extern lv_obj_t *uic_MainImagetachConnNo;
extern lv_obj_t *uic_MainPanelTachAlarmIndicatorIcon2;
extern lv_obj_t *uic_MainPanelTachAlarmIndicatorIcon1;
extern lv_obj_t *uic_MainLabelTachValue;
extern lv_obj_t *uic_MainLabelTachUnit;
extern lv_obj_t *uic_MainLabelSpeedTitle;
extern lv_obj_t *uic_MainPanelSpeedAlarmIndicatorIcon1;
extern lv_obj_t *uic_MainPanelSpeedAlarmIndicatorIcon2;
extern lv_obj_t *uic_MainLabelSpeedValue;
extern lv_obj_t *uic_MainLabelSpeedUnit;
extern lv_obj_t *uic_MainContainerLimit;
extern lv_obj_t *uic_MainPanelLimitIndicatorIcon1;
extern lv_obj_t *uic_MainPanelLimitIndicatorIcon2;
extern lv_obj_t *uic_MainContainerStateREADY;
extern lv_obj_t *uic_MainButtonREADYStage;
extern lv_obj_t *uic_MainContainerStateSTAGED;
extern lv_obj_t *uic_MainButtonSTAGEDCancel;
extern lv_obj_t *uic_MainContainerStatePULLING;
extern lv_obj_t *uic_MainButtonPULLINGStop;
extern lv_obj_t *uic_MainContainerStatePULLEND;
extern lv_obj_t *uic_MainButtonPULLENDDiscard;
extern lv_obj_t *uic_MainButtonPULLENDSave;
extern lv_obj_t *uic_MainContainerStateEMERGENCYSTOP;
extern lv_obj_t *uic_MainContainerRelays;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon1;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon2;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon3;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon4;
extern lv_obj_t *uic_MainPanelwhite;
extern lv_obj_t *uic_MainBarDistanceProgress;
extern lv_obj_t *uic_MainBarDistanceAlarm1;
extern lv_obj_t *uic_MainBarDistanceAlarm2;
extern lv_obj_t *uic_MainContainerDistanceTitleLabel;
extern lv_obj_t *uic_MainLabelDistanceTitle;
extern lv_obj_t *uic_DistanceAlarmTriangle1;
extern lv_obj_t *uic_DistanceAlarmTriangle2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

