// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "../ui.h"

lv_obj_t *uic_ExportScreenLabeldoneButtonLabel;
lv_obj_t *uic_ExportScreenButtondoneButton;
lv_obj_t *uic_ExportScreenPanelinstructionPanel;
lv_obj_t *ui_ScreenExportScreen = NULL;lv_obj_t *ui_ExportScreenPanelinstructionPanel = NULL;lv_obj_t *ui_ExportScreenContainerButtonContainer1 = NULL;lv_obj_t *ui_ExportScreenButtondoneButton = NULL;lv_obj_t *ui_ExportScreenLabeldoneButtonLabel = NULL;
// event funtions
void ui_event_ScreenExportScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      exportScreenLoaded( e );
}
}

void ui_event_ExportScreenButtondoneButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      exportDoneButtonClicked( e );
      _ui_screen_change( &ui_ScreenPullHistoryScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenPullHistoryScreen_screen_init);
}
}

// build funtions

void ui_ScreenExportScreen_screen_init(void)
{
ui_ScreenExportScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenExportScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenExportScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScreenExportScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_ScreenExportScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenExportScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenExportScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenExportScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExportScreenPanelinstructionPanel = lv_obj_create(ui_ScreenExportScreen);
lv_obj_set_width( ui_ExportScreenPanelinstructionPanel, lv_pct(100));
lv_obj_set_flex_grow( ui_ExportScreenPanelinstructionPanel, 1);
lv_obj_set_x( ui_ExportScreenPanelinstructionPanel, -39 );
lv_obj_set_y( ui_ExportScreenPanelinstructionPanel, -2 );
lv_obj_set_align( ui_ExportScreenPanelinstructionPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ExportScreenPanelinstructionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ExportScreenPanelinstructionPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ExportScreenPanelinstructionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ExportScreenPanelinstructionPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ExportScreenPanelinstructionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExportScreenContainerButtonContainer1 = lv_obj_create(ui_ScreenExportScreen);
lv_obj_remove_style_all(ui_ExportScreenContainerButtonContainer1);
lv_obj_set_height( ui_ExportScreenContainerButtonContainer1, 60);
lv_obj_set_width( ui_ExportScreenContainerButtonContainer1, lv_pct(100));
lv_obj_set_x( ui_ExportScreenContainerButtonContainer1, 34 );
lv_obj_set_y( ui_ExportScreenContainerButtonContainer1, 146 );
lv_obj_set_align( ui_ExportScreenContainerButtonContainer1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ExportScreenContainerButtonContainer1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ExportScreenContainerButtonContainer1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ExportScreenContainerButtonContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ExportScreenButtondoneButton = lv_btn_create(ui_ExportScreenContainerButtonContainer1);
lv_obj_set_height( ui_ExportScreenButtondoneButton, 50);
lv_obj_set_width( ui_ExportScreenButtondoneButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_ExportScreenButtondoneButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ExportScreenButtondoneButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ExportScreenButtondoneButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ExportScreenButtondoneButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Blue);
ui_object_set_themeable_style_property(ui_ExportScreenButtondoneButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Blue);
lv_obj_set_style_text_font(ui_ExportScreenButtondoneButton, &ui_font_BIO_SEMIBOLD_6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExportScreenLabeldoneButtonLabel = lv_label_create(ui_ExportScreenButtondoneButton);
lv_obj_set_width( ui_ExportScreenLabeldoneButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ExportScreenLabeldoneButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ExportScreenLabeldoneButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ExportScreenLabeldoneButtonLabel,"Done");

lv_obj_add_event_cb(ui_ExportScreenButtondoneButton, ui_event_ExportScreenButtondoneButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenExportScreen, ui_event_ScreenExportScreen, LV_EVENT_ALL, NULL);
uic_ExportScreenPanelinstructionPanel = ui_ExportScreenPanelinstructionPanel;
uic_ExportScreenButtondoneButton = ui_ExportScreenButtondoneButton;
uic_ExportScreenLabeldoneButtonLabel = ui_ExportScreenLabeldoneButtonLabel;

}

void ui_ScreenExportScreen_screen_destroy(void)
{
   if (ui_ScreenExportScreen) lv_obj_del(ui_ScreenExportScreen);

// NULL screen variables
ui_ScreenExportScreen= NULL;
uic_ExportScreenPanelinstructionPanel= NULL;
ui_ExportScreenPanelinstructionPanel= NULL;
ui_ExportScreenContainerButtonContainer1= NULL;
uic_ExportScreenButtondoneButton= NULL;
ui_ExportScreenButtondoneButton= NULL;
uic_ExportScreenLabeldoneButtonLabel= NULL;
ui_ExportScreenLabeldoneButtonLabel= NULL;

}
