// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef UI_SCREENEXPORTSCREEN_H
#define UI_SCREENEXPORTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenExportScreen
extern void ui_ScreenExportScreen_screen_init(void);
extern void ui_ScreenExportScreen_screen_destroy(void);
extern void ui_event_ScreenExportScreen( lv_event_t * e);
extern lv_obj_t *ui_ScreenExportScreen;
extern lv_obj_t *ui_ExportScreenPanelinstructionPanel;
extern lv_obj_t *ui_ExportScreenContainerButtonContainer1;
extern void ui_event_ExportScreenButtondoneButton( lv_event_t * e);
extern lv_obj_t *ui_ExportScreenButtondoneButton;
extern lv_obj_t *ui_ExportScreenLabeldoneButtonLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ExportScreenPanelinstructionPanel;
extern lv_obj_t *uic_ExportScreenButtondoneButton;
extern lv_obj_t *uic_ExportScreenLabeldoneButtonLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

