// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef UI_SCREENPULLHISTORYSCREEN_H
#define UI_SCREENPULLHISTORYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPullHistoryScreen
extern void ui_ScreenPullHistoryScreen_screen_init(void);
extern void ui_ScreenPullHistoryScreen_screen_destroy(void);
extern void ui_event_ScreenPullHistoryScreen( lv_event_t * e);
extern lv_obj_t *ui_ScreenPullHistoryScreen;
extern lv_obj_t *ui_PullHistoryScreenPanelTablePanel;
extern lv_obj_t *ui_PullHistoryScreenContainerButtonContainer;
extern void ui_event_PullHistoryScreenButtondeletePullHistoryButton( lv_event_t * e);
extern lv_obj_t *ui_PullHistoryScreenButtondeletePullHistoryButton;
extern lv_obj_t *ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel;
extern void ui_event_PullHistoryScreenButtondeletePullHistoryButton1( lv_event_t * e);
extern lv_obj_t *ui_PullHistoryScreenButtondeletePullHistoryButton1;
extern lv_obj_t *ui_PullHistoryScreenLabeldeletePullHistoryButtonLabel1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_PullHistoryScreenPanelTablePanel;
extern lv_obj_t *uic_PullHistoryScreenContainerButtonContainer;
extern lv_obj_t *uic_PullHistoryScreenButtondeletePullHistoryButton;
extern lv_obj_t *uic_PullHistoryScreenLabeldeletePullHistoryButtonLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

