#include <Arduino.h>
#include <SPI.h>
#include <lvgl/lvgl.h>

#include "Config.h"
#include "PreferencesManager.h"
#include "PullStateManager.h"
#include "ScreenUpdater.h"
#include "SpeedModule.h"
#include "StateManager.h"
#include "dev_utils/benchmark.h"
#include "display/backlight.h"
#include "display/display.h"
#include "touch/touchscreen.h"

#ifdef DEVELOPMENT_MODE
#include "dev_utils/DevSimulator.h"
#endif

// UI generated by Squareline
#include "../ui/ui.h"

// LVGL buffers and drivers
static lv_disp_draw_buf_t draw_buf;
static lv_color_t buf1[800 * 40];
static lv_disp_drv_t disp_drv;
static lv_indev_drv_t indev_drv;

//========================================================================
// LVGL Callbacks
//========================================================================

// Display flushing callback for LVGL
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p) {
  uint32_t w = (area->x2 - area->x1 + 1);
  uint32_t h = (area->y2 - area->y1 + 1);

  lcd.startWrite();
  lcd.setAddrWindow(area->x1, area->y1, w, h);
  lcd.pushPixels((uint16_t *)color_p, w * h);
  lcd.endWrite();

  lv_disp_flush_ready(disp);
}

// Touchpad reading callback for LVGL
void my_touchpad_read(lv_indev_drv_t *indev_drv, lv_indev_data_t *data) {
  // uint16_t touchX, touchY, touchZ;
  // bool touched = touch.readTouchPoint(&touchX, &touchY, &touchZ);

  // if (touched) {
  //   data->state = LV_INDEV_STATE_PR;
  //   data->point.x = touchX;
  //   data->point.y = touchY;
  // } else {
  //   data->state = LV_INDEV_STATE_REL;
  // }
}

//========================================================================
// Core System Functions
//========================================================================

// LVGL task handler
void lvgl_task(void *parameter) {
  while (1) {
    lv_timer_handler();
    delay(5);
  }
}

// Initialize LVGL
void init_lvgl() {
  lv_init();

  // Initialize display buffer
  // lv_disp_draw_buf_init(&draw_buf, buf1, NULL, 800 * 10);
  lv_disp_draw_buf_init(&draw_buf, buf1, NULL, 800 * 40);

  // Initialize display driver
  lv_disp_drv_init(&disp_drv);
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.draw_buf = &draw_buf;
  disp_drv.hor_res = 800;
  disp_drv.ver_res = 480;
  lv_disp_drv_register(&disp_drv);

  // Initialize input device driver
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = my_touchpad_read;
  lv_indev_drv_register(&indev_drv);
}

//========================================================================
// Arduino Main Functions
//========================================================================

void setup() {
  Serial.begin(115200);
  delay(1000);

  StateManager::loadPreferences();
  // Preferences prefs;
  // prefs.begin("touch_cal", false);
  // prefs.clear();  // ⚠️ This erases everything in "touch_cal"
  // prefs.end();

  Serial.println("Starting M4 7-inch RGB Display UI: M4_MCU_2025...");
  Serial.print("Version: ");
  Serial.println(VERSION);
  Serial.print("Build Date: ");
  Serial.println(__DATE__ " " __TIME__);

  init_display();
  touch::init_touch();

  init_lvgl();
  ui_init();
  PullStateManager::init();
  SpeedModule::begin();

  StateManager::prefs().driverNumber = 1;
  StateManager::savePreferences();

  xTaskCreatePinnedToCore(lvgl_task, "lvgl_task", 4096, NULL, 1, NULL, 1);
  Serial.println("Setup complete");
}

bool isMainScreenReady() {
  return uic_MainLabelSpeedValue && uic_MainLabelDistanceValue && uic_MainLabelTachValue && uic_MainLabelDriverName &&
         uic_MainLabelDriverNumber && uic_MainLabelClassName;
}

unsigned long lastScreenUpdate = 0;

void loop() {
  lv_timer_handler();
  updateBacklight();
  benchmark_update();
  PullStateManager::update();
  SpeedModule::tick();

#ifdef DEVELOPMENT_MODE
  devSimulator::update();
#endif

  unsigned long now = millis();
  if (isMainScreenReady() && now - lastScreenUpdate >= SCREEN_UPDATE_INTERVAL_MS) {
    lastScreenUpdate = now;
    updateMainScreen();
  }

  // TouchScreen::setRecalibrationFlag();

  delay(5);
  uint16_t x, y, z;
  if (touch::readRaw(x, y, z)) {
    Serial.print("Touch: ");
    Serial.print("x = ");
    Serial.print(x);
    Serial.print(", y = ");
    Serial.print(y);
    Serial.print(", z = ");
    Serial.println(z);
    delay(30);
  }
}