#include <Arduino.h>
#include <lvgl/lvgl.h>

#include "Config.h"
#include "PreferencesManager.h"
#include "PullStateManager.h"
#include "ScreenUpdater.h"
#include "SpeedModule.h"
#include "StateManager.h"
#include "dev_utils/benchmark.h"
#include "display/backlight.h"
#include "display/display.h"
#include "touch/calibration.h"
#include "touch/touch.h"
#include "display/lvgl_callbacks.h"

// UI generated by Squareline
#include "../ui/ui.h"

void setup() {
  Serial.begin(SERIAL_BAUD_RATE);
  delay(1000);

  StateManager::loadPreferences();
  // Preferences prefs;
  // prefs.begin("touch_cal", false);
  // prefs.clear();  // ⚠️ This erases everything in "touch_cal"
  // prefs.end();

  Serial.println("Starting M4 7-inch RGB Display UI: M4_MCU_2025...");
  Serial.print("Version: ");
  Serial.println(VERSION);
  Serial.print("Build Date: ");
  Serial.println(__DATE__ " " __TIME__);

  init_display();
  init_touch();

  init_lvgl();
  ui_init();
  PullStateManager::init();
  SpeedModule::begin();

  StateManager::prefs().driverNumber = 1;
  StateManager::savePreferences();

  xTaskCreatePinnedToCore(lvgl_task, "lvgl_task", 4096, NULL, 1, NULL, 1);
  Serial.println("Setup complete");
}

bool isMainScreenReady() {
  return uic_MainLabelSpeedValue && uic_MainLabelDistanceValue && uic_MainLabelTachValue && uic_MainLabelDriverName &&
         uic_MainLabelDriverNumber && uic_MainLabelClassName;
}

unsigned long lastScreenUpdate = 0;

void loop() {
  lv_timer_handler();
  updateBacklight();
  benchmark_update();
  PullStateManager::update();
  SpeedModule::tick();

  unsigned long now = millis();
  if (isMainScreenReady() && now - lastScreenUpdate >= SCREEN_UPDATE_INTERVAL_MS) {
    lastScreenUpdate = now;
    updateMainScreen();
  }
  TouchScreen::setRecalibrationFlag();

  delay(5);
}