// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_MainContainerDistanceProgression;
lv_obj_t *ui_MainContainerRaceFlag;
lv_obj_t *ui_MainPanelwhite;
lv_obj_t *ui_MainPanelblack;
lv_obj_t *ui_MainPanelwhite1;
lv_obj_t *ui_MainPanelblack1;
lv_obj_t *ui_MainPanelwhite2;
lv_obj_t *ui_MainPanelblack2;
lv_obj_t *ui_MainPanelwhite3;
lv_obj_t *ui_MainPanelblack3;
lv_obj_t *ui_MainPanelwhite4;
lv_obj_t *ui_MainPanelblack4;
lv_obj_t *ui_MainPanelwhite5;
lv_obj_t *ui_MainPanelblack5;
lv_obj_t *ui_MainPanelwhite6;
lv_obj_t *ui_MainPanelblack6;
lv_obj_t *ui_MainPanelwhite7;
lv_obj_t *ui_MainPanelblack7;
lv_obj_t *ui_MainPanelwhite8;
lv_obj_t *ui_MainPanelblack8;
lv_obj_t *ui_MainPanelwhite9;
lv_obj_t *ui_MainPanelblack9;
lv_obj_t *ui_MainPanelwhite10;
lv_obj_t *ui_MainPanelblack10;
lv_obj_t *ui_MainContainerDistanceProgressBar;
lv_obj_t *ui_MainBarDistanceProgress;
lv_obj_t *ui_MainBarDistanceAlarm1;
lv_obj_t *ui_MainBarDistanceAlarm2;
lv_obj_t *ui_MainContainerMainContainer;
lv_obj_t *ui_MainContainerTop;
lv_obj_t *ui_MainContainerHeader;
lv_obj_t *ui_MainContainerClass;
lv_obj_t *ui_MainContainerClassTitleLabel;
lv_obj_t *ui_MainLabelClassTitle;
lv_obj_t *ui_MainLabelClassWeight;
lv_obj_t *ui_MainContainerClassNameLabel;
lv_obj_t *ui_MainLabelClassName;
lv_obj_t *ui_MainContainerSettingsButton;
void ui_event_MainButtonSettings( lv_event_t * e);
lv_obj_t *ui_MainButtonSettings;
lv_obj_t *ui_MainContainerDriver;
lv_obj_t *ui_MainContainerDriverTitleLabel;
lv_obj_t *ui_MainLabelDriverTitle;
lv_obj_t *ui_MainLabelDriverNumber;
lv_obj_t *ui_MainContainerDriverNameLabel;
lv_obj_t *ui_MainLabelDriverName;
lv_obj_t *ui_MainContainerDriverChangeButton;
lv_obj_t *ui_MainButtonDriverChange;
lv_obj_t *ui_MainContainerDistance;
lv_obj_t *ui_MainLabelDistanceValue;
lv_obj_t *ui_MainLabelDistanceUnit;
lv_obj_t *ui_MainContainerMid;
lv_obj_t *ui_MainContainerTach;
lv_obj_t *ui_MainContainerTachTitleLabel;
lv_obj_t *ui_MainLabelTachTitle;
lv_obj_t *ui_MainContainerTachData;
lv_obj_t *ui_MainContainerTachAlarmIndicator;
lv_obj_t *ui_MainPanelTachAlarmIndicatorIcon;
lv_obj_t *ui_MainLabelTachValue;
lv_obj_t *ui_MainLabelTachUnit;
lv_obj_t *ui_MainContainerSpeed;
lv_obj_t *ui_MainContainerSpeedTitleLabel;
lv_obj_t *ui_MainLabelSpeedTitle;
lv_obj_t *ui_MainContainerSpeedData;
lv_obj_t *ui_MainContainerSpeedAlarmIndicator;
lv_obj_t *ui_MainPanelSpeedAlarmIndicatorIcon;
lv_obj_t *ui_MainLabelSpeedValue;
lv_obj_t *ui_MainLabelSpeedUnit;
lv_obj_t *ui_MainContainerBottom;
lv_obj_t *ui_MainContainerLimit;
lv_obj_t *ui_MainContainerLimitTitleLabel;
lv_obj_t *ui_MainLabelLimitTitle;
lv_obj_t *ui_MainContainerLimitData;
lv_obj_t *ui_MainContainerLimitIndicators1;
lv_obj_t *ui_MainLabelLimitIndicator1;
lv_obj_t *ui_MainPanelLimitIndicatorIcon1;
lv_obj_t *ui_MainContainerLimitIndicators2;
lv_obj_t *ui_MainLabelLimitIndicator2;
lv_obj_t *ui_MainPanelLimitIndicatorIcon2;
lv_obj_t *ui_MainContainerPullStateControls;
lv_obj_t *ui_MainButtonStage;
lv_obj_t *ui_MainLabelButtonStage;
lv_obj_t *ui_MainButtonStaged;
lv_obj_t *ui_MainLabelButtonStaged;
lv_obj_t *ui_MainLabelButtonStagedCancel;
lv_obj_t *ui_MainButtonStop;
lv_obj_t *ui_MainLabelButtonStop;
lv_obj_t *ui_MainContainerRelays;
lv_obj_t *ui_MainContainerRelaysTitleLabel;
lv_obj_t *ui_MainLabelRelaysTitle;
lv_obj_t *ui_MainContainerRelaysData;
lv_obj_t *ui_MainContainerRelayIndicators1;
lv_obj_t *ui_MainLabelRelayIndicator1;
lv_obj_t *ui_MainPanelRelayIndicatorIcon1;
lv_obj_t *ui_MainContainerRelayIndicators2;
lv_obj_t *ui_MainLabelRelayIndicator2;
lv_obj_t *ui_MainPanelRelayIndicatorIcon2;
lv_obj_t *ui_MainContainerRelayIndicators3;
lv_obj_t *ui_MainLabelRelayIndicator3;
lv_obj_t *ui_MainPanelRelayIndicatorIcon3;
lv_obj_t *ui_MainContainerRelayIndicators4;
lv_obj_t *ui_MainLabelRelayIndicator4;
lv_obj_t *ui_MainPanelRelayIndicatorIcon4;
// CUSTOM VARIABLES
lv_obj_t *uic_ScreenMain;
lv_obj_t *uic_DistanceProgression;
lv_obj_t *uic_MainContainerRaceFlag;
lv_obj_t *uic_MainPanelwhite;
lv_obj_t *uic_MainContainerDistanceProgressBar;
lv_obj_t *uic_MainBarDistanceProgress;
lv_obj_t *uic_MainBarDistanceAlarm1;
lv_obj_t *uic_MainBarDistanceAlarm2;
lv_obj_t *uic_MainContainerMainContainer;
lv_obj_t *uic_MainContainerTop;
lv_obj_t *uic_MainContainerHeader;
lv_obj_t *uic_MainContainerClass;
lv_obj_t *uic_MainContainerClassTitleLabel;
lv_obj_t *uic_MainLabelClassTitle;
lv_obj_t *uic_MainLabelClassWeight;
lv_obj_t *uic_MainContainerClassNameLabel;
lv_obj_t *uic_MainLabelClassName;
lv_obj_t *uic_MainContainerSettingsButton;
lv_obj_t *uic_MainButtonSettings;
lv_obj_t *uic_MainContainerDriver;
lv_obj_t *uic_MainContainerDriverTitleLabel;
lv_obj_t *uic_MainLabelDriverTitle;
lv_obj_t *uic_MainLabelDriverNumber;
lv_obj_t *uic_MainContainerDriverNameLabel;
lv_obj_t *uic_MainLabelDriverName;
lv_obj_t *uic_MainContainerDriverChangeButton;
lv_obj_t *uic_MainButtonDriverChange;
lv_obj_t *uic_MainContainerDistance;
lv_obj_t *uic_MainLabelDistanceValue;
lv_obj_t *uic_MainLabelDistanceUnit;
lv_obj_t *uic_MainContainerMid;
lv_obj_t *uic_MainContainerTach;
lv_obj_t *uic_MainContainerTachTitleLabel;
lv_obj_t *uic_MainLabelTachTitle;
lv_obj_t *uic_MainContainerTachData;
lv_obj_t *uic_MainContainerTachAlarmIndicator;
lv_obj_t *uic_MainPanelTachAlarmIndicatorIcon;
lv_obj_t *uic_MainLabelTachValue;
lv_obj_t *uic_MainLabelTachUnit;
lv_obj_t *uic_MainContainerSpeed;
lv_obj_t *uic_MainContainerSpeedTitleLabel;
lv_obj_t *uic_MainLabelSpeedTitle;
lv_obj_t *uic_MainContainerSpeedData;
lv_obj_t *uic_MainContainerSpeedAlarmIndicator;
lv_obj_t *uic_MainPanelSpeedAlarmIndicatorIcon;
lv_obj_t *uic_MainLabelSpeedValue;
lv_obj_t *uic_MainLabelSpeedUnit;
lv_obj_t *uic_MainContainerBottom;
lv_obj_t *uic_MainContainerLimit;
lv_obj_t *uic_MainContainerLimitTitleLabel;
lv_obj_t *uic_MainLabelLimitTitle;
lv_obj_t *uic_MainContainerLimitData;
lv_obj_t *uic_MainContainerLimitIndicators1;
lv_obj_t *uic_MainLabelLimitIndicator1;
lv_obj_t *uic_MainPanelLimitIndicatorIcon1;
lv_obj_t *uic_MainContainerLimitIndicators2;
lv_obj_t *uic_MainLabelLimitIndicator2;
lv_obj_t *uic_MainPanelLimitIndicatorIcon2;
lv_obj_t *uic_MainContainerPullStateControls;
lv_obj_t *uic_MainButtonStage;
lv_obj_t *uic_MainLabelButtonStage;
lv_obj_t *uic_MainButtonStaged;
lv_obj_t *uic_MainLabelButtonStaged;
lv_obj_t *uic_MainLabelButtonStagedCancel;
lv_obj_t *uic_MainButtonStop;
lv_obj_t *uic_MainLabelButtonStop;
lv_obj_t *uic_MainContainerRelays;
lv_obj_t *uic_MainContainerRelaysTitleLabel;
lv_obj_t *uic_MainLabelRelaysTitle;
lv_obj_t *uic_MainContainerRelaysData;
lv_obj_t *uic_MainContainerRelayIndicators1;
lv_obj_t *uic_MainLabelRelayIndicator1;
lv_obj_t *uic_MainPanelRelayIndicatorIcon1;
lv_obj_t *uic_MainContainerRelayIndicators2;
lv_obj_t *uic_MainLabelRelayIndicator2;
lv_obj_t *uic_MainPanelRelayIndicatorIcon2;
lv_obj_t *uic_MainContainerRelayIndicators3;
lv_obj_t *uic_MainLabelRelayIndicator3;
lv_obj_t *uic_MainPanelRelayIndicatorIcon3;
lv_obj_t *uic_MainContainerRelayIndicators4;
lv_obj_t *uic_MainLabelRelayIndicator4;
lv_obj_t *uic_MainPanelRelayIndicatorIcon4;

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
void ui_event_ScreenSettings( lv_event_t * e);
lv_obj_t *ui_ScreenSettings;
lv_obj_t *ui_SettingsTabviewSettingsView;
lv_obj_t *ui_SettingsTabpageGeneral;
lv_obj_t *ui_SettingsPanelGeneralSettings;
lv_obj_t *ui_SettingsContainerUnitsSetting;
lv_obj_t *ui_SettingsLabelUnitsMetric;
void ui_event_SettingsSwitchUnits( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchUnits;
lv_obj_t *ui_SettingsLabelUnitsImperial;
lv_obj_t *ui_SettingsContainerBenchmarkSetting;
void ui_event_SettingsSwitchBenchmark( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchBenchmark;
lv_obj_t *ui_SettingsLabelBenchmarkTitle;
lv_obj_t *ui_SettingsContainerBrightnessSetting;
lv_obj_t *ui_SettingsLabelBrightnessTitle;
void ui_event_SettingsSliderSlider1( lv_event_t * e);
lv_obj_t *ui_SettingsSliderSlider1;
lv_obj_t *ui_SettingsLabelBrightness;
lv_obj_t *ui_SettingsTabpageSpeed_and_Distance;
lv_obj_t *ui_SettingsTabpageTach;
lv_obj_t *ui_SettingsTabpageRelays_and_Limits;
lv_obj_t *ui_SettingsPanelConnectionRLM;
lv_obj_t *ui_SettingsContainerContainer8;
lv_obj_t *ui_SettingsContainerContainer9;
lv_obj_t *ui_SettingsButtonButton1;
lv_obj_t *ui_SettingsLabelLabel6;
lv_obj_t *ui_SettingsLabelLabel7;
lv_obj_t *ui_SettingsPanelRelayLimitSettings;
lv_obj_t *ui_SettingsContainerRelaySettings;
lv_obj_t *ui_SettingsLabellblRelays;
lv_obj_t *ui_SettingsContainercontainerEnableRelay;
lv_obj_t *ui_SettingsSwitchSwitch1;
lv_obj_t *ui_SettingsLabelLabel1;
lv_obj_t *ui_SettingsContainerrealayversion1;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch1;
lv_obj_t *ui_SettingsLabelLabel21;
lv_obj_t *ui_SettingsSwitchSwitch3;
lv_obj_t *ui_SettingsDropdownDropdown1;
lv_obj_t *ui_SettingsDropdownDropdown2;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch2;
lv_obj_t *ui_SettingsLabelLabel5;
lv_obj_t *ui_SettingsSwitchSwitch2;
lv_obj_t *ui_SettingsDropdownDropdown3;
lv_obj_t *ui_SettingsDropdownDropdown4;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch3;
lv_obj_t *ui_SettingsLabelLabel8;
lv_obj_t *ui_SettingsSwitchSwitch5;
lv_obj_t *ui_SettingsDropdownDropdown5;
lv_obj_t *ui_SettingsDropdownDropdown6;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch4;
lv_obj_t *ui_SettingsLabelLabel9;
lv_obj_t *ui_SettingsSwitchSwitch6;
lv_obj_t *ui_SettingsDropdownDropdown7;
lv_obj_t *ui_SettingsDropdownDropdown8;
lv_obj_t *ui_SettingsContainercontainerLimitSettings;
lv_obj_t *ui_SettingsLabelLabel2;
lv_obj_t *ui_SettingsContainercontainerEnableLimit;
lv_obj_t *ui_SettingsSwitchSwitch4;
lv_obj_t *ui_SettingsLabelLabel3;
lv_obj_t *ui_SettingsPanelPanel1;
lv_obj_t *ui_SettingsTabpageJudge;
lv_obj_t *ui_SettingsTabpageSafety_and_Displays;
lv_obj_t *ui_SettingsTabpageAbout;
lv_obj_t *ui_SettingsPanelAboutInfo;
lv_obj_t *ui_SettingsLabelAboutTitle;
lv_obj_t *ui_SettingsLabelVersionTitle;
lv_obj_t *ui_SettingsLabelVersionData;
lv_obj_t *ui_SettingsLabelBuildDateTitle;
lv_obj_t *ui_SettingsLabelBuildDateData;
lv_obj_t *ui_SettingsLabelDevelopedByTitle;
lv_obj_t *ui_SettingsLabelDevelopedByData;
lv_obj_t *ui_SettingsLabelInfoTitle;
lv_obj_t *ui_SettingsLabelInfoData;
lv_obj_t *ui_SettingsLabelSupportTitle;
lv_obj_t *ui_SettingsLabelSupportData;
lv_obj_t *ui_SettingsLabelCopyrightData;
void ui_event_SettingsTabpageExit( lv_event_t * e);
lv_obj_t *ui_SettingsTabpageExit;
lv_obj_t *ui_SettingsLabelBountyMessage;
void ui_event_SettingsButtonReturnHome( lv_event_t * e);
lv_obj_t *ui_SettingsButtonReturnHome;
lv_obj_t *ui_SettingsLabelButtonReturnHome;
void ui_event_SettingsContainerExitButtonOverlay( lv_event_t * e);
lv_obj_t *ui_SettingsContainerExitButtonOverlay;
// CUSTOM VARIABLES
lv_obj_t *uic_ScreenSettings;
lv_obj_t *uic_SettingsTabviewSettingsView;
lv_obj_t *uic_SettingsPanelGeneralSettings;
lv_obj_t *uic_SettingsContainerUnitsSetting;
lv_obj_t *uic_SettingsLabelUnitsMetric;
lv_obj_t *uic_SettingsSwitchUnits;
lv_obj_t *uic_SettingsLabelUnitsImperial;
lv_obj_t *uic_SettingsContainerBenchmarkSetting;
lv_obj_t *uic_SettingsSwitchBenchmark;
lv_obj_t *uic_SettingsLabelBenchmarkTitle;
lv_obj_t *uic_SettingsContainerBrightnessSetting;
lv_obj_t *uic_SettingsLabelBrightnessTitle;
lv_obj_t *uic_SettingsLabelBrightness;
lv_obj_t *uic_SettingsPanelConnectionRLM;
lv_obj_t *uic_SettingsPanelRelayLimitSettings;
lv_obj_t *uic_SettingsContainerRelaySettings;
lv_obj_t *uic_SettingsLabellblRelays;
lv_obj_t *uic_SettingsContainercontainerEnableRelay;
lv_obj_t *uic_SettingsContainercontainterRelaySwitch1;
lv_obj_t *uic_SettingsContainercontainerLimitSettings;
lv_obj_t *uic_SettingsContainercontainerEnableLimit;
lv_obj_t *uic_SettingsPanelAboutInfo;
lv_obj_t *uic_SettingsLabelAboutTitle;
lv_obj_t *uic_SettingsLabelVersionTitle;
lv_obj_t *uic_SettingsLabelVersionData;
lv_obj_t *uic_SettingsLabelBuildDateTitle;
lv_obj_t *uic_SettingsLabelBuildDateData;
lv_obj_t *uic_SettingsLabelDevelopedByTitle;
lv_obj_t *uic_SettingsLabelDevelopedByData;
lv_obj_t *uic_SettingsLabelInfoTitle;
lv_obj_t *uic_SettingsLabelInfoData;
lv_obj_t *uic_SettingsLabelSupportData;
lv_obj_t *uic_SettingsLabelCopyrightData;
lv_obj_t *uic_SettingsLabelBountyMessage;
lv_obj_t *uic_SettingsButtonReturnHome;
lv_obj_t *uic_SettingsLabelButtonReturnHome;
lv_obj_t *uic_SettingsContainerExitButtonOverlay;

// EVENTS
lv_obj_t *ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainButtonSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
}

void ui_event_ScreenSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      updateAboutPageInfo( e );
}
}

void ui_event_SettingsSwitchUnits( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      unitsToggle( e );
}
}

void ui_event_SettingsSwitchBenchmark( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      benchmarkToggle( e );
}
}

void ui_event_SettingsSliderSlider1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeBrightness( e );
}
}

void ui_event_SettingsTabpageExit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
}
}

void ui_event_SettingsButtonReturnHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
}
}

void ui_event_SettingsContainerExitButtonOverlay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenMain_screen_init();
ui_ScreenSettings_screen_init();
ui_Startevents___initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenMain);
}
