// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain( lv_event_t * e);
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_MainContainerDistanceProgression;
lv_obj_t *ui_MainContainerRaceFlag;
lv_obj_t *ui_MainPanelwhite;
lv_obj_t *ui_MainPanelblack;
lv_obj_t *ui_MainPanelwhite1;
lv_obj_t *ui_MainPanelblack1;
lv_obj_t *ui_MainPanelwhite2;
lv_obj_t *ui_MainPanelblack2;
lv_obj_t *ui_MainPanelwhite3;
lv_obj_t *ui_MainPanelblack3;
lv_obj_t *ui_MainPanelwhite4;
lv_obj_t *ui_MainPanelblack4;
lv_obj_t *ui_MainPanelwhite5;
lv_obj_t *ui_MainPanelblack5;
lv_obj_t *ui_MainPanelwhite6;
lv_obj_t *ui_MainPanelblack6;
lv_obj_t *ui_MainPanelwhite7;
lv_obj_t *ui_MainPanelblack7;
lv_obj_t *ui_MainPanelwhite8;
lv_obj_t *ui_MainPanelblack8;
lv_obj_t *ui_MainPanelwhite9;
lv_obj_t *ui_MainPanelblack9;
lv_obj_t *ui_MainPanelwhite10;
lv_obj_t *ui_MainPanelblack10;
lv_obj_t *ui_MainContainerDistanceProgressBar;
lv_obj_t *ui_MainBarDistanceProgress;
lv_obj_t *ui_MainBarDistanceAlarm1;
lv_obj_t *ui_MainBarDistanceAlarm2;
lv_obj_t *ui_MainContainerMainContainer;
lv_obj_t *ui_MainContainerTop;
lv_obj_t *ui_MainContainerHeader;
lv_obj_t *ui_MainContainerClass;
lv_obj_t *ui_MainContainerClassTitleLabel;
lv_obj_t *ui_MainLabelClassTitle;
lv_obj_t *ui_MainLabelClassWeight;
lv_obj_t *ui_MainContainerClassNameLabel;
lv_obj_t *ui_MainLabelClassName;
lv_obj_t *ui_MainContainerSettingsButton;
void ui_event_MainButtonSettings( lv_event_t * e);
lv_obj_t *ui_MainButtonSettings;
lv_obj_t *ui_MainContainerDriver;
lv_obj_t *ui_MainContainerDriverTitleLabel;
lv_obj_t *ui_MainLabelDriverTitle;
lv_obj_t *ui_MainLabelDriverNumber;
lv_obj_t *ui_MainContainerDriverNameLabel;
lv_obj_t *ui_MainLabelDriverName;
lv_obj_t *ui_MainContainerDriverChangeButton;
lv_obj_t *ui_MainButtonDriverChange;
lv_obj_t *ui_MainContainerDistance;
lv_obj_t *ui_MainLabelDistanceValue;
lv_obj_t *ui_MainLabelDistanceUnit;
lv_obj_t *ui_MainContainerMid;
lv_obj_t *ui_MainContainerTach;
lv_obj_t *ui_MainContainerTachTitleLabel;
lv_obj_t *ui_MainLabelTachTitle;
lv_obj_t *ui_MainContainerTachData;
lv_obj_t *ui_MainContainerTachAlarmIndicator;
lv_obj_t *ui_MainPanelTachAlarmIndicatorIcon;
lv_obj_t *ui_MainLabelTachValue;
lv_obj_t *ui_MainLabelTachUnit;
lv_obj_t *ui_MainContainerSpeed;
lv_obj_t *ui_MainContainerSpeedTitleLabel;
lv_obj_t *ui_MainLabelSpeedTitle;
lv_obj_t *ui_MainContainerSpeedData;
lv_obj_t *ui_MainContainerSpeedAlarmIndicator;
lv_obj_t *ui_MainPanelSpeedAlarmIndicatorIcon;
lv_obj_t *ui_MainLabelSpeedValue;
lv_obj_t *ui_MainLabelSpeedUnit;
lv_obj_t *ui_MainContainerBottom;
lv_obj_t *ui_MainContainerLimit;
lv_obj_t *ui_MainContainerLimitTitleLabel;
lv_obj_t *ui_MainLabelLimitTitle;
lv_obj_t *ui_MainContainerLimitData;
lv_obj_t *ui_MainContainerLimitIndicators1;
lv_obj_t *ui_MainLabelLimitIndicator1;
lv_obj_t *ui_MainPanelLimitIndicatorIcon1;
lv_obj_t *ui_MainContainerLimitIndicators2;
lv_obj_t *ui_MainLabelLimitIndicator2;
lv_obj_t *ui_MainPanelLimitIndicatorIcon2;
lv_obj_t *ui_MainContainerPullStateControls;
lv_obj_t *ui_MainContainerStateREADY;
void ui_event_MainButtonREADYStage( lv_event_t * e);
lv_obj_t *ui_MainButtonREADYStage;
lv_obj_t *ui_MainLabelButtonStage;
lv_obj_t *ui_MainContainerStateSTAGED;
void ui_event_MainButtonSTAGEDCancel( lv_event_t * e);
lv_obj_t *ui_MainButtonSTAGEDCancel;
lv_obj_t *ui_MainLabelButtonStaged;
lv_obj_t *ui_MainLabelButtonStagedCancel;
lv_obj_t *ui_MainContainerStatePULLING;
void ui_event_MainButtonPULLINGStop( lv_event_t * e);
lv_obj_t *ui_MainButtonPULLINGStop;
lv_obj_t *ui_MainLabelButtonStop;
lv_obj_t *ui_MainContainerStatePULLEND;
void ui_event_MainButtonPULLENDDiscard( lv_event_t * e);
lv_obj_t *ui_MainButtonPULLENDDiscard;
lv_obj_t *ui_MainLabelButtonStage1;
void ui_event_MainButtonPULLENDSave( lv_event_t * e);
lv_obj_t *ui_MainButtonPULLENDSave;
lv_obj_t *ui_MainLabelButtonStaged2;
void ui_event_MainContainerStateEMERGENCYSTOP( lv_event_t * e);
lv_obj_t *ui_MainContainerStateEMERGENCYSTOP;
lv_obj_t *ui_MainButtonPULLINGStop1;
lv_obj_t *ui_MainLabelButtonStop1;
lv_obj_t *ui_MainContainerRelays;
lv_obj_t *ui_MainContainerRelaysTitleLabel;
lv_obj_t *ui_MainLabelRelaysTitle;
lv_obj_t *ui_MainContainerRelaysData;
lv_obj_t *ui_MainContainerRelayIndicators1;
lv_obj_t *ui_MainLabelRelayIndicator1;
lv_obj_t *ui_MainPanelRelayIndicatorIcon1;
lv_obj_t *ui_MainContainerRelayIndicators2;
lv_obj_t *ui_MainLabelRelayIndicator2;
lv_obj_t *ui_MainPanelRelayIndicatorIcon2;
lv_obj_t *ui_MainContainerRelayIndicators3;
lv_obj_t *ui_MainLabelRelayIndicator3;
lv_obj_t *ui_MainPanelRelayIndicatorIcon3;
lv_obj_t *ui_MainContainerRelayIndicators4;
lv_obj_t *ui_MainLabelRelayIndicator4;
lv_obj_t *ui_MainPanelRelayIndicatorIcon4;
lv_obj_t *ui_MainContainerDistanceTitleLabel;
lv_obj_t *ui_MainLabelDistanceTitle;
// CUSTOM VARIABLES
lv_obj_t *uic_ScreenMain;
lv_obj_t *uic_MainPanelwhite;
lv_obj_t *uic_MainBarDistanceProgress;
lv_obj_t *uic_MainBarDistanceAlarm1;
lv_obj_t *uic_MainBarDistanceAlarm2;
lv_obj_t *uic_MainLabelClassWeight;
lv_obj_t *uic_MainLabelClassName;
lv_obj_t *uic_MainButtonSettings;
lv_obj_t *uic_MainLabelDriverNumber;
lv_obj_t *uic_MainLabelDriverName;
lv_obj_t *uic_MainButtonDriverChange;
lv_obj_t *uic_MainLabelDistanceValue;
lv_obj_t *uic_MainLabelDistanceUnit;
lv_obj_t *uic_MainContainerTach;
lv_obj_t *uic_MainLabelTachTitle;
lv_obj_t *uic_MainPanelTachAlarmIndicatorIcon;
lv_obj_t *uic_MainLabelTachValue;
lv_obj_t *uic_MainLabelTachUnit;
lv_obj_t *uic_MainLabelSpeedTitle;
lv_obj_t *uic_MainPanelSpeedAlarmIndicatorIcon;
lv_obj_t *uic_MainLabelSpeedValue;
lv_obj_t *uic_MainLabelSpeedUnit;
lv_obj_t *uic_MainContainerLimit;
lv_obj_t *uic_MainPanelLimitIndicatorIcon1;
lv_obj_t *uic_MainPanelLimitIndicatorIcon2;
lv_obj_t *uic_MainContainerStateREADY;
lv_obj_t *uic_MainButtonREADYStage;
lv_obj_t *uic_MainContainerStateSTAGED;
lv_obj_t *uic_MainButtonSTAGEDCancel;
lv_obj_t *uic_MainContainerStatePULLING;
lv_obj_t *uic_MainButtonPULLINGStop;
lv_obj_t *uic_MainContainerStatePULLEND;
lv_obj_t *uic_MainButtonPULLENDDiscard;
lv_obj_t *uic_MainButtonPULLENDSave;
lv_obj_t *uic_MainContainerStateEMERGENCYSTOP;
lv_obj_t *uic_MainContainerRelays;
lv_obj_t *uic_MainPanelRelayIndicatorIcon1;
lv_obj_t *uic_MainPanelRelayIndicatorIcon2;
lv_obj_t *uic_MainPanelRelayIndicatorIcon3;
lv_obj_t *uic_MainPanelRelayIndicatorIcon4;
lv_obj_t *uic_MainContainerDistanceTitleLabel;
lv_obj_t *uic_MainLabelDistanceTitle;

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
void ui_event_ScreenSettings( lv_event_t * e);
lv_obj_t *ui_ScreenSettings;
lv_obj_t *ui_SettingsTabviewSettingsView;
lv_obj_t *ui_SettingsTabpageGeneral;
lv_obj_t *ui_SettingsPanelGeneralSettings;
lv_obj_t *ui_SettingsContainertracklength;
lv_obj_t *ui_SettingsLabelLabel10;
lv_obj_t *ui_SettingsContainerSettingGeneral1;
void ui_event_SettingsSwitchUnitsToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchUnitsToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle1;
lv_obj_t *ui_SettingsContainerSettingGeneral2;
void ui_event_SettingsSwitchBenchmarkToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchBenchmarkToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle2;
lv_obj_t *ui_SettingsContainerBrightnessSetting;
lv_obj_t *ui_SettingsLabelBrightnessTitle;
void ui_event_SettingsSliderBrightnessSlider( lv_event_t * e);
lv_obj_t *ui_SettingsSliderBrightnessSlider;
lv_obj_t *ui_SettingsLabelBrightness;
lv_obj_t *ui_SettingsContainerSettingGeneral3;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle3;
void ui_event_SettingsTextareaTrackLengthText( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaTrackLengthText;
lv_obj_t *ui_SettingsLabelTrackLengthUnitsTitle;
lv_obj_t *ui_SettingsContainerSettingGeneral4;
void ui_event_SettingsSwitchTachToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchTachToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle4;
void ui_event_SettingsButtonHelpTach( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpTach;
lv_obj_t *ui_SettingsLabelLabel11;
lv_obj_t *ui_SettingsContainerSettingGeneral5;
void ui_event_SettingsSwitchLimitToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchLimitToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle5;
void ui_event_SettingsButtonHelpLimit( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpLimit;
lv_obj_t *ui_SettingsLabelLabel12;
lv_obj_t *ui_SettingsContainerSettingGeneral6;
void ui_event_SettingsSwitchRelaysToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchRelaysToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle6;
void ui_event_SettingsButtonHelpRelay( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpRelay;
lv_obj_t *ui_SettingsLabelLabel13;
lv_obj_t *ui_SettingsContainerSettingGeneral7;
void ui_event_SettingsSwitchHelpIconVisibiltyToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchHelpIconVisibiltyToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle7;
lv_obj_t *ui_SettingsContainerSettingGeneral8;
void ui_event_SettingsButtonButton5( lv_event_t * e);
lv_obj_t *ui_SettingsButtonButton5;
lv_obj_t *ui_SettingsLabelLabel30;
lv_obj_t *ui_SettingsTabpageSpeed_and_Distance;
lv_obj_t *ui_SettingsPanelCalibrationNumberPanel;
lv_obj_t *ui_SettingsLabelSpeedandDistanceTitle;
lv_obj_t *ui_SettingsContainerCalibrationNumber;
lv_obj_t *ui_SettingsLabelCalibrationNumberTitle;
void ui_event_SettingsTextareaCalibrationNumberTextArea( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaCalibrationNumberTextArea;
void ui_event_SettingsButtonButton4( lv_event_t * e);
lv_obj_t *ui_SettingsButtonButton4;
lv_obj_t *ui_SettingsLabelLabel15;
void ui_event_SettingsButtonHelpCalibrationNumberText( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpCalibrationNumberText;
lv_obj_t *ui_SettingsLabelLabel14;
lv_obj_t *ui_SettingsPanelGearToothCalculatorPanel;
lv_obj_t *ui_SettingsContainerCalc;
lv_obj_t *ui_SettingsLabelCalibrationNumberTitle1;
lv_obj_t *ui_SettingsLabelLabel17;
void ui_event_SettingsTextareaCalibrationCalculatorNumTeethTextArea( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaCalibrationCalculatorNumTeethTextArea;
lv_obj_t *ui_SettingsLabelLabel19;
void ui_event_SettingsTextareaCalibrationCalculatorWheelDiameterTextArea( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaCalibrationCalculatorWheelDiameterTextArea;
lv_obj_t *ui_SettingsLabelLabel18;
void ui_event_SettingsTextareaCalibrationCalculatorGearRatioTextArea( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaCalibrationCalculatorGearRatioTextArea;
lv_obj_t *ui_SettingsLabelGearToothCalculatorPulses;
void ui_event_SettingsButtonCalculateButton( lv_event_t * e);
lv_obj_t *ui_SettingsButtonCalculateButton;
lv_obj_t *ui_SettingsLabelLabel29;
void ui_event_SettingsButtonSaveCalibrationCalculatorButton( lv_event_t * e);
lv_obj_t *ui_SettingsButtonSaveCalibrationCalculatorButton;
lv_obj_t *ui_SettingsLabelLabel4;
void ui_event_SettingsButtonHelpCalibrationNumberText1( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpCalibrationNumberText1;
lv_obj_t *ui_SettingsLabelLabel16;
lv_obj_t *ui_SettingsPanelAutoCalibration;
lv_obj_t *ui_SettingsContainerCalc1;
lv_obj_t *ui_SettingsLabelCalibrationNumberTitle2;
void ui_event_SettingsButtonStartAutoDriveButton( lv_event_t * e);
lv_obj_t *ui_SettingsButtonStartAutoDriveButton;
lv_obj_t *ui_SettingsLabelLabel20;
lv_obj_t *ui_SettingsLabelLabel22;
lv_obj_t *ui_SettingsLabelAutoDriveCurrentPulses;
void ui_event_SettingsButtonFinishAutoDriveButton( lv_event_t * e);
lv_obj_t *ui_SettingsButtonFinishAutoDriveButton;
lv_obj_t *ui_SettingsLabelLabel23;
void ui_event_SettingsButtonSaveCalibrationAutoDriveButton( lv_event_t * e);
lv_obj_t *ui_SettingsButtonSaveCalibrationAutoDriveButton;
lv_obj_t *ui_SettingsLabelLabel24;
void ui_event_SettingsButtonHelpCalibrationNumberText2( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpCalibrationNumberText2;
lv_obj_t *ui_SettingsLabelLabel25;
lv_obj_t *ui_SettingsPanelCalibrationPresetsPanel;
lv_obj_t *ui_SettingsContainerCalibrationNumber1;
lv_obj_t *ui_SettingsLabelCalibrationNumberTitle3;
void ui_event_SettingsButtonButton2( lv_event_t * e);
lv_obj_t *ui_SettingsButtonButton2;
lv_obj_t *ui_SettingsLabelLabel26;
void ui_event_SettingsButtonButton3( lv_event_t * e);
lv_obj_t *ui_SettingsButtonButton3;
lv_obj_t *ui_SettingsLabelLabel28;
void ui_event_SettingsButtonHelpCalibrationNumberText3( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpCalibrationNumberText3;
lv_obj_t *ui_SettingsLabelLabel27;
lv_obj_t *ui_SettingsTabpageTach;
lv_obj_t *ui_SettingsPanelPanel2;
lv_obj_t *ui_SettingsContainerSettingTach1;
void ui_event_SettingsSwitchTachAutoConnectToggle( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchTachAutoConnectToggle;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle9;
void ui_event_SettingsButtonTachAutoConnectHelp( lv_event_t * e);
lv_obj_t *ui_SettingsButtonTachAutoConnectHelp;
lv_obj_t *ui_SettingsLabelLabel32;
lv_obj_t *ui_SettingsTabpageAlarms;
lv_obj_t *ui_SettingsPanelPanel3;
lv_obj_t *ui_SettingsContainerSettingGeneral10;
lv_obj_t *ui_SettingsLabelSettingsGeneralTitle10;
lv_obj_t *ui_SettingsDropdownDropdown9;
void ui_event_SettingsButtonHelpTach2( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpTach2;
lv_obj_t *ui_SettingsLabelLabel33;
lv_obj_t *ui_SettingsContainerDistanceAlarms;
lv_obj_t *ui_SettingsContainerAlarmDistance1;
void ui_event_SettingsSwitchAlarmDistanceToggle1( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmDistanceToggle1;
lv_obj_t *ui_SettingsLabelAlarmDistanceTitle1;
void ui_event_SettingsTextareaAlarmDistanceValueTextArea1( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmDistanceValueTextArea1;
lv_obj_t *ui_SettingsDropdownAlarmDistanceDropdown1;
lv_obj_t *ui_SettingsContainerAlarmDistance2;
void ui_event_SettingsSwitchAlarmDistanceToggle2( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmDistanceToggle2;
lv_obj_t *ui_SettingsLabelAlarmDistanceTitle2;
void ui_event_SettingsTextareaAlarmDistanceValueTextArea2( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmDistanceValueTextArea2;
lv_obj_t *ui_SettingsDropdownAlarmDistanceDropdown2;
lv_obj_t *ui_SettingsContainerSpeedAlarms;
lv_obj_t *ui_SettingsContainerAlarmSpeed1;
void ui_event_SettingsSwitchAlarmSpeedToggle1( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmSpeedToggle1;
lv_obj_t *ui_SettingsLabelAlarmSpeedTitle1;
void ui_event_SettingsTextareaAlarmSpeedValueTextArea1( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmSpeedValueTextArea1;
lv_obj_t *ui_SettingsDropdownAlarmSpeedDropdown1;
lv_obj_t *ui_SettingsContainerAlarmSpeed2;
void ui_event_SettingsSwitchAlarmSpeedToggle2( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmSpeedToggle2;
lv_obj_t *ui_SettingsLabelAlarmSpeedTitle2;
void ui_event_SettingsTextareaAlarmSpeedValueTextArea2( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmSpeedValueTextArea2;
lv_obj_t *ui_SettingsDropdownAlarmSpeedDropdown2;
lv_obj_t *ui_SettingsContainerRPMAlarms;
lv_obj_t *ui_SettingsContainerAlarmRPM1;
void ui_event_SettingsSwitchAlarmRPMToggle1( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmRPMToggle1;
lv_obj_t *ui_SettingsLabelAlarmRPMTitle1;
void ui_event_SettingsTextareaAlarmRPMValueTextArea1( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmRPMValueTextArea1;
lv_obj_t *ui_SettingsDropdownAlarmRPMDropdown1;
lv_obj_t *ui_SettingsContainerAlarmRPM2;
void ui_event_SettingsSwitchAlarmRPMToggle2( lv_event_t * e);
lv_obj_t *ui_SettingsSwitchAlarmRPMToggle2;
lv_obj_t *ui_SettingsLabelAlarmRPMTitle2;
void ui_event_SettingsTextareaAlarmRPMValueTextArea2( lv_event_t * e);
lv_obj_t *ui_SettingsTextareaAlarmRPMValueTextArea2;
lv_obj_t *ui_SettingsDropdownAlarmRPMDropdown2;
lv_obj_t *ui_SettingsTabpageRelays_and_Limits;
lv_obj_t *ui_SettingsPanelConnectionRLM;
lv_obj_t *ui_SettingsContainerContainer8;
lv_obj_t *ui_SettingsContainerContainer9;
lv_obj_t *ui_SettingsButtonButton1;
lv_obj_t *ui_SettingsLabelLabel6;
lv_obj_t *ui_SettingsLabelLabel7;
lv_obj_t *ui_SettingsPanelRelayLimitSettings;
lv_obj_t *ui_SettingsContainerRelaySettings;
lv_obj_t *ui_SettingsLabellblRelays;
lv_obj_t *ui_SettingsContainercontainerEnableRelay;
lv_obj_t *ui_SettingsSwitchSwitch1;
lv_obj_t *ui_SettingsLabelLabel1;
lv_obj_t *ui_SettingsContainerrealayversion1;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch1;
lv_obj_t *ui_SettingsLabelLabel21;
lv_obj_t *ui_SettingsSwitchSwitch3;
lv_obj_t *ui_SettingsDropdownDropdown1;
lv_obj_t *ui_SettingsDropdownDropdown2;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch2;
lv_obj_t *ui_SettingsLabelLabel5;
lv_obj_t *ui_SettingsSwitchSwitch2;
lv_obj_t *ui_SettingsDropdownDropdown3;
lv_obj_t *ui_SettingsDropdownDropdown4;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch3;
lv_obj_t *ui_SettingsLabelLabel8;
lv_obj_t *ui_SettingsSwitchSwitch5;
lv_obj_t *ui_SettingsDropdownDropdown5;
lv_obj_t *ui_SettingsDropdownDropdown6;
lv_obj_t *ui_SettingsContainercontainterRelaySwitch4;
lv_obj_t *ui_SettingsLabelLabel9;
lv_obj_t *ui_SettingsSwitchSwitch6;
lv_obj_t *ui_SettingsDropdownDropdown7;
lv_obj_t *ui_SettingsDropdownDropdown8;
lv_obj_t *ui_SettingsContainercontainerLimitSettings;
lv_obj_t *ui_SettingsLabelLabel2;
lv_obj_t *ui_SettingsContainercontainerEnableLimit;
lv_obj_t *ui_SettingsSwitchSwitch4;
lv_obj_t *ui_SettingsLabelLabel3;
lv_obj_t *ui_SettingsPanelPanel1;
lv_obj_t *ui_SettingsTabpageJudge;
lv_obj_t *ui_SettingsTabpageSafety_and_Displays;
lv_obj_t *ui_SettingsPanelConnectionRLM2;
lv_obj_t *ui_SettingsContainerContainer3;
lv_obj_t *ui_SettingsContainerContainer1;
lv_obj_t *ui_SettingsButtonButton7;
lv_obj_t *ui_SettingsLabelLabel36;
lv_obj_t *ui_SettingsLabelLabel31;
void ui_event_SettingsButtonHelpPairDisplays( lv_event_t * e);
lv_obj_t *ui_SettingsButtonHelpPairDisplays;
lv_obj_t *ui_SettingsLabelLabel34;
lv_obj_t *ui_SettingsPanelDeviceTable;
lv_obj_t *ui_SettingsTabpageAbout;
lv_obj_t *ui_SettingsPanelAboutInfo;
lv_obj_t *ui_SettingsLabelAboutTitle;
lv_obj_t *ui_SettingsLabelVersionTitle;
lv_obj_t *ui_SettingsLabelVersionData;
lv_obj_t *ui_SettingsLabelBuildDateTitle;
lv_obj_t *ui_SettingsLabelBuildDateData;
lv_obj_t *ui_SettingsLabelDevelopedByTitle;
lv_obj_t *ui_SettingsLabelDevelopedByData;
lv_obj_t *ui_SettingsLabelInfoTitle;
lv_obj_t *ui_SettingsLabelInfoData;
lv_obj_t *ui_SettingsLabelSupportTitle;
lv_obj_t *ui_SettingsLabelSupportData;
lv_obj_t *ui_SettingsLabelCopyrightData;
void ui_event_SettingsTabpageExit( lv_event_t * e);
lv_obj_t *ui_SettingsTabpageExit;
lv_obj_t *ui_SettingsLabelBountyMessage;
void ui_event_SettingsButtonReturnHome( lv_event_t * e);
lv_obj_t *ui_SettingsButtonReturnHome;
lv_obj_t *ui_SettingsLabelButtonReturnHome;
void ui_event_SettingsKeyboardSettingsNumberKeyboard( lv_event_t * e);
lv_obj_t *ui_SettingsKeyboardSettingsNumberKeyboard;
// CUSTOM VARIABLES
lv_obj_t *uic_ScreenSettings;
lv_obj_t *uic_SettingsTabviewSettingsView;
lv_obj_t *uic_SettingsPanelGeneralSettings;
lv_obj_t *uic_SettingsSwitchUnitsToggle;
lv_obj_t *uic_SettingsSwitchBenchmarkToggle;
lv_obj_t *uic_SettingsContainerBrightnessSetting;
lv_obj_t *uic_SettingsLabelBrightnessTitle;
lv_obj_t *uic_SettingsSliderBrightnessSlider;
lv_obj_t *uic_SettingsLabelBrightness;
lv_obj_t *uic_SettingsTextareaTrackLengthText;
lv_obj_t *uic_SettingsLabelTrackLengthUnitsTitle;
lv_obj_t *uic_SettingsSwitchTachToggle;
lv_obj_t *uic_SettingsSwitchLimitToggle;
lv_obj_t *uic_SettingsSwitchRelaysToggle;
lv_obj_t *uic_SettingsTextareaCalibrationNumberTextArea;
lv_obj_t *uic_SettingsButtonHelpCalibrationNumberText;
lv_obj_t *uic_SettingsTextareaCalibrationCalculatorNumTeethTextArea;
lv_obj_t *uic_SettingsTextareaCalibrationCalculatorWheelDiameterTextArea;
lv_obj_t *uic_SettingsTextareaCalibrationCalculatorGearRatioTextArea;
lv_obj_t *uic_SettingsButtonCalculateButton;
lv_obj_t *uic_SettingsSwitchTachAutoConnectToggle;
lv_obj_t *uic_SettingsButtonTachAutoConnectHelp;
lv_obj_t *uic_SettingsSwitchAlarmDistanceToggle1;
lv_obj_t *uic_SettingsDropdownAlarmDistanceDropdown1;
lv_obj_t *uic_SettingsSwitchAlarmSpeedToggle1;
lv_obj_t *uic_SettingsContainerAlarmRPM1;
lv_obj_t *uic_SettingsPanelConnectionRLM;
lv_obj_t *uic_SettingsPanelRelayLimitSettings;
lv_obj_t *uic_SettingsContainerRelaySettings;
lv_obj_t *uic_SettingsLabellblRelays;
lv_obj_t *uic_SettingsContainercontainerEnableRelay;
lv_obj_t *uic_SettingsContainercontainterRelaySwitch1;
lv_obj_t *uic_SettingsContainercontainerLimitSettings;
lv_obj_t *uic_SettingsContainercontainerEnableLimit;
lv_obj_t *uic_SettingsPanelDeviceTable;
lv_obj_t *uic_SettingsPanelAboutInfo;
lv_obj_t *uic_SettingsLabelAboutTitle;
lv_obj_t *uic_SettingsLabelVersionTitle;
lv_obj_t *uic_SettingsLabelVersionData;
lv_obj_t *uic_SettingsLabelBuildDateTitle;
lv_obj_t *uic_SettingsLabelBuildDateData;
lv_obj_t *uic_SettingsLabelDevelopedByTitle;
lv_obj_t *uic_SettingsLabelDevelopedByData;
lv_obj_t *uic_SettingsLabelInfoTitle;
lv_obj_t *uic_SettingsLabelInfoData;
lv_obj_t *uic_SettingsLabelSupportData;
lv_obj_t *uic_SettingsLabelCopyrightData;
lv_obj_t *uic_SettingsLabelBountyMessage;
lv_obj_t *uic_SettingsButtonReturnHome;
lv_obj_t *uic_SettingsLabelButtonReturnHome;
lv_obj_t *uic_SettingsKeyboardSettingsNumberKeyboard;

// EVENTS
lv_obj_t *ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenMain( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      loadMainScreen( e );
}
}

void ui_event_MainButtonSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
}

void ui_event_MainButtonREADYStage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      READYStageBtnPressed( e );
}
}

void ui_event_MainButtonSTAGEDCancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      STAGEDCancelBtnPressed( e );
}
}

void ui_event_MainButtonPULLINGStop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      PULLINGStopBtnPressed( e );
}
}

void ui_event_MainButtonPULLENDDiscard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      PULLENDDiscardBtnPressed( e );
}
}

void ui_event_MainButtonPULLENDSave( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      PULLENDSaveBtnPressed( e );
}
}

void ui_event_MainContainerStateEMERGENCYSTOP( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      EMERGENCYSTOPResetBtnPressed( e );
}
}

void ui_event_ScreenSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      SettingsScreenLoaded( e );
      CreateDeviceTable( e );
}
}

void ui_event_SettingsSwitchUnitsToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchUnitsChange( e );
}
}

void ui_event_SettingsSwitchBenchmarkToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchBenchmarkChange( e );
}
}

void ui_event_SettingsSliderBrightnessSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSliderBrightnessChange( e );
}
}

void ui_event_SettingsTextareaTrackLengthText( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsTrackLengthText( e );
}
}

void ui_event_SettingsSwitchTachToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchTachChange( e );
      _ui_flag_modify( ui_MainContainerTach, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_SettingsButtonHelpTach( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      EnableTachHelpButtonPressed( e );
}
}

void ui_event_SettingsSwitchLimitToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchLimitChange( e );
      _ui_flag_modify( ui_MainContainerLimit, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_SettingsButtonHelpLimit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      EnableLimitsHelpButtonPressed( e );
}
}

void ui_event_SettingsSwitchRelaysToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_SettingsButtonHelpRelay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      EnableRelayHelpButtonPressed( e );
}
}

void ui_event_SettingsSwitchHelpIconVisibiltyToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchHelpIconVisibility( e );
}
}

void ui_event_SettingsButtonButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      RecalibrateTouch( e );
}
}

void ui_event_SettingsTextareaCalibrationNumberTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaCalibrationNumberTextArea);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsButtonButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveCalibrationNumberButton( e );
}
}

void ui_event_SettingsButtonHelpCalibrationNumberText( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPCalNumber( e );
}
}

void ui_event_SettingsTextareaCalibrationCalculatorNumTeethTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaCalibrationCalculatorNumTeethTextArea);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsTextareaCalibrationCalculatorWheelDiameterTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaCalibrationCalculatorWheelDiameterTextArea);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsTextareaCalibrationCalculatorGearRatioTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaCalibrationCalculatorGearRatioTextArea);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsButtonCalculateButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CalculateCalibrationCalculatorNumberButton( e );
}
}

void ui_event_SettingsButtonSaveCalibrationCalculatorButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveCalibrationCalculatorNumberButton( e );
}
}

void ui_event_SettingsButtonHelpCalibrationNumberText1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPGearToothCalc( e );
}
}

void ui_event_SettingsButtonStartAutoDriveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      StartAutoDriveButtonPressed( e );
      _ui_state_modify( ui_SettingsButtonStartAutoDriveButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsButtonFinishAutoDriveButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsButtonFinishAutoDriveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      FinishAutoDriveButtonPressed( e );
      _ui_state_modify( ui_SettingsButtonStartAutoDriveButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsButtonFinishAutoDriveButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
}

void ui_event_SettingsButtonSaveCalibrationAutoDriveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveCalibrationAutoDriveNumberButton( e );
}
}

void ui_event_SettingsButtonHelpCalibrationNumberText2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPAutoCal( e );
}
}

void ui_event_SettingsButtonButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveRadarCalibration( e );
}
}

void ui_event_SettingsButtonButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveGPSCalibration( e );
}
}

void ui_event_SettingsButtonHelpCalibrationNumberText3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPPresetCalNumber( e );
}
}

void ui_event_SettingsSwitchTachAutoConnectToggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchBenchmarkChange( e );
}
}

void ui_event_SettingsButtonTachAutoConnectHelp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPTachAutoConnect( e );
}
}

void ui_event_SettingsButtonHelpTach2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPAlarmPresets( e );
}
}

void ui_event_SettingsSwitchAlarmDistanceToggle1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmDistanceValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmDistanceDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmDistanceDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmDistanceValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmDistanceValueTextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmDistanceValueTextArea1);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsSwitchAlarmDistanceToggle2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmDistanceValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmDistanceDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmDistanceDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmDistanceValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmDistanceValueTextArea2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmDistanceValueTextArea2);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsSwitchAlarmSpeedToggle1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmSpeedValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmSpeedDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmSpeedDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmSpeedValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmSpeedValueTextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmSpeedValueTextArea1);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsSwitchAlarmSpeedToggle2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmSpeedValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmSpeedDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmSpeedDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmSpeedValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmSpeedValueTextArea2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmSpeedValueTextArea2);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsSwitchAlarmRPMToggle1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmRPMValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmRPMDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmRPMDropdown1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmRPMValueTextArea1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmRPMValueTextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmRPMValueTextArea1);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsSwitchAlarmRPMToggle2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      SettingsSwitchRelaysChange( e );
      _ui_flag_modify( ui_MainContainerRelays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsTextareaAlarmRPMValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_SettingsDropdownAlarmRPMDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_SettingsDropdownAlarmRPMDropdown2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SettingsTextareaAlarmRPMValueTextArea2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_SettingsTextareaAlarmRPMValueTextArea2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_SettingsKeyboardSettingsNumberKeyboard,  ui_SettingsTextareaAlarmRPMValueTextArea2);
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SettingsButtonHelpPairDisplays( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      HELPTachAutoConnect( e );
}
}

void ui_event_SettingsTabpageExit( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
}
}

void ui_event_SettingsButtonReturnHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenMain_screen_init);
}
}

void ui_event_SettingsKeyboardSettingsNumberKeyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_SettingsKeyboardSettingsNumberKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_SettingsTabviewSettingsView, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenMain_screen_init();
ui_ScreenSettings_screen_init();
ui_Startevents___initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenMain);
}
