// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef _M4_MCU_2025_UI_H
#define _M4_MCU_2025_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenMain.h"
#include "screens/ui_ScreenSettings.h"
#include "screens/ui_ScreenPullHistoryScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_iconsettings44px_png);   // assets/iconSettings44px.png
LV_IMG_DECLARE( ui_img_table_helemet_42x42_png);   // assets/table_helemet_42x42.png
LV_IMG_DECLARE( ui_img_iconchangedriver44px_png);   // assets/iconChangeDriver44px.png

// FONTS
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_10);
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_6);
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_8);
LV_FONT_DECLARE( ui_font_BIO_EXTRABOLD_19);
LV_FONT_DECLARE( ui_font_BIO_SEMIBOLD_6);
LV_FONT_DECLARE( ui_font_BIO_SEMIBOLD_7);
LV_FONT_DECLARE( ui_font_HH13);
LV_FONT_DECLARE( ui_font_HH24);
LV_FONT_DECLARE( ui_font_HH40);
LV_FONT_DECLARE( ui_font_HH8);
LV_FONT_DECLARE( ui_font_INFORME_24);
LV_FONT_DECLARE( ui_font_INFORME_40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
