// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef _M4_MCU_2025_UI_H
#define _M4_MCU_2025_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_MainContainerDistanceProgression;
extern lv_obj_t *ui_MainContainerRaceFlag;
extern lv_obj_t *ui_MainPanelwhite;
extern lv_obj_t *ui_MainPanelblack;
extern lv_obj_t *ui_MainPanelwhite1;
extern lv_obj_t *ui_MainPanelblack1;
extern lv_obj_t *ui_MainPanelwhite2;
extern lv_obj_t *ui_MainPanelblack2;
extern lv_obj_t *ui_MainPanelwhite3;
extern lv_obj_t *ui_MainPanelblack3;
extern lv_obj_t *ui_MainPanelwhite4;
extern lv_obj_t *ui_MainPanelblack4;
extern lv_obj_t *ui_MainPanelwhite5;
extern lv_obj_t *ui_MainPanelblack5;
extern lv_obj_t *ui_MainPanelwhite6;
extern lv_obj_t *ui_MainPanelblack6;
extern lv_obj_t *ui_MainPanelwhite7;
extern lv_obj_t *ui_MainPanelblack7;
extern lv_obj_t *ui_MainPanelwhite8;
extern lv_obj_t *ui_MainPanelblack8;
extern lv_obj_t *ui_MainPanelwhite9;
extern lv_obj_t *ui_MainPanelblack9;
extern lv_obj_t *ui_MainPanelwhite10;
extern lv_obj_t *ui_MainPanelblack10;
extern lv_obj_t *ui_MainContainerDistanceProgressBar;
extern lv_obj_t *ui_MainBarDistanceProgress;
extern lv_obj_t *ui_MainBarDistanceAlarm1;
extern lv_obj_t *ui_MainBarDistanceAlarm2;
extern lv_obj_t *ui_MainContainerMainContainer;
extern lv_obj_t *ui_MainContainerTop;
extern lv_obj_t *ui_MainContainerHeader;
extern lv_obj_t *ui_MainContainerClass;
extern lv_obj_t *ui_MainContainerClassTitleLabel;
extern lv_obj_t *ui_MainLabelClassTitle;
extern lv_obj_t *ui_MainLabelClassWeight;
extern lv_obj_t *ui_MainContainerClassNameLabel;
extern lv_obj_t *ui_MainLabelClassName;
extern lv_obj_t *ui_MainContainerSettingsButton;
void ui_event_MainButtonSettings( lv_event_t * e);
extern lv_obj_t *ui_MainButtonSettings;
extern lv_obj_t *ui_MainContainerDriver;
extern lv_obj_t *ui_MainContainerDriverTitleLabel;
extern lv_obj_t *ui_MainLabelDriverTitle;
extern lv_obj_t *ui_MainLabelDriverNumber;
extern lv_obj_t *ui_MainContainerDriverNameLabel;
extern lv_obj_t *ui_MainLabelDriverName;
extern lv_obj_t *ui_MainContainerDriverChangeButton;
extern lv_obj_t *ui_MainButtonDriverChange;
extern lv_obj_t *ui_MainContainerDistance;
extern lv_obj_t *ui_MainLabelDistanceValue;
extern lv_obj_t *ui_MainLabelDistanceUnit;
extern lv_obj_t *ui_MainContainerMid;
extern lv_obj_t *ui_MainContainerTach;
extern lv_obj_t *ui_MainContainerTachTitleLabel;
extern lv_obj_t *ui_MainLabelTachTitle;
extern lv_obj_t *ui_MainContainerTachData;
extern lv_obj_t *ui_MainContainerTachAlarmIndicator;
extern lv_obj_t *ui_MainPanelTachAlarmIndicatorIcon;
extern lv_obj_t *ui_MainLabelTachValue;
extern lv_obj_t *ui_MainLabelTachUnit;
extern lv_obj_t *ui_MainContainerSpeed;
extern lv_obj_t *ui_MainContainerSpeedTitleLabel;
extern lv_obj_t *ui_MainLabelSpeedTitle;
extern lv_obj_t *ui_MainContainerSpeedData;
extern lv_obj_t *ui_MainContainerSpeedAlarmIndicator;
extern lv_obj_t *ui_MainPanelSpeedAlarmIndicatorIcon;
extern lv_obj_t *ui_MainLabelSpeedValue;
extern lv_obj_t *ui_MainLabelSpeedUnit;
extern lv_obj_t *ui_MainContainerBottom;
extern lv_obj_t *ui_MainContainerLimit;
extern lv_obj_t *ui_MainContainerLimitTitleLabel;
extern lv_obj_t *ui_MainLabelLimitTitle;
extern lv_obj_t *ui_MainContainerLimitData;
extern lv_obj_t *ui_MainContainerLimitIndicators1;
extern lv_obj_t *ui_MainLabelLimitIndicator1;
extern lv_obj_t *ui_MainPanelLimitIndicatorIcon1;
extern lv_obj_t *ui_MainContainerLimitIndicators2;
extern lv_obj_t *ui_MainLabelLimitIndicator2;
extern lv_obj_t *ui_MainPanelLimitIndicatorIcon2;
extern lv_obj_t *ui_MainContainerPullStateControls;
extern lv_obj_t *ui_MainButtonStage;
extern lv_obj_t *ui_MainLabelButtonStage;
extern lv_obj_t *ui_MainButtonStaged;
extern lv_obj_t *ui_MainLabelButtonStaged;
extern lv_obj_t *ui_MainLabelButtonStagedCancel;
extern lv_obj_t *ui_MainButtonStop;
extern lv_obj_t *ui_MainLabelButtonStop;
extern lv_obj_t *ui_MainContainerRelays;
extern lv_obj_t *ui_MainContainerRelaysTitleLabel;
extern lv_obj_t *ui_MainLabelRelaysTitle;
extern lv_obj_t *ui_MainContainerRelaysData;
extern lv_obj_t *ui_MainContainerRelayIndicators1;
extern lv_obj_t *ui_MainLabelRelayIndicator1;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon1;
extern lv_obj_t *ui_MainContainerRelayIndicators2;
extern lv_obj_t *ui_MainLabelRelayIndicator2;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon2;
extern lv_obj_t *ui_MainContainerRelayIndicators3;
extern lv_obj_t *ui_MainLabelRelayIndicator3;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon3;
extern lv_obj_t *ui_MainContainerRelayIndicators4;
extern lv_obj_t *ui_MainLabelRelayIndicator4;
extern lv_obj_t *ui_MainPanelRelayIndicatorIcon4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenMain;
extern lv_obj_t *uic_DistanceProgression;
extern lv_obj_t *uic_MainContainerRaceFlag;
extern lv_obj_t *uic_MainPanelwhite;
extern lv_obj_t *uic_MainContainerDistanceProgressBar;
extern lv_obj_t *uic_MainBarDistanceProgress;
extern lv_obj_t *uic_MainBarDistanceAlarm1;
extern lv_obj_t *uic_MainBarDistanceAlarm2;
extern lv_obj_t *uic_MainContainerMainContainer;
extern lv_obj_t *uic_MainContainerTop;
extern lv_obj_t *uic_MainContainerHeader;
extern lv_obj_t *uic_MainContainerClass;
extern lv_obj_t *uic_MainContainerClassTitleLabel;
extern lv_obj_t *uic_MainLabelClassTitle;
extern lv_obj_t *uic_MainLabelClassWeight;
extern lv_obj_t *uic_MainContainerClassNameLabel;
extern lv_obj_t *uic_MainLabelClassName;
extern lv_obj_t *uic_MainContainerSettingsButton;
extern lv_obj_t *uic_MainButtonSettings;
extern lv_obj_t *uic_MainContainerDriver;
extern lv_obj_t *uic_MainContainerDriverTitleLabel;
extern lv_obj_t *uic_MainLabelDriverTitle;
extern lv_obj_t *uic_MainLabelDriverNumber;
extern lv_obj_t *uic_MainContainerDriverNameLabel;
extern lv_obj_t *uic_MainLabelDriverName;
extern lv_obj_t *uic_MainContainerDriverChangeButton;
extern lv_obj_t *uic_MainButtonDriverChange;
extern lv_obj_t *uic_MainContainerDistance;
extern lv_obj_t *uic_MainLabelDistanceValue;
extern lv_obj_t *uic_MainLabelDistanceUnit;
extern lv_obj_t *uic_MainContainerMid;
extern lv_obj_t *uic_MainContainerTach;
extern lv_obj_t *uic_MainContainerTachTitleLabel;
extern lv_obj_t *uic_MainLabelTachTitle;
extern lv_obj_t *uic_MainContainerTachData;
extern lv_obj_t *uic_MainContainerTachAlarmIndicator;
extern lv_obj_t *uic_MainPanelTachAlarmIndicatorIcon;
extern lv_obj_t *uic_MainLabelTachValue;
extern lv_obj_t *uic_MainLabelTachUnit;
extern lv_obj_t *uic_MainContainerSpeed;
extern lv_obj_t *uic_MainContainerSpeedTitleLabel;
extern lv_obj_t *uic_MainLabelSpeedTitle;
extern lv_obj_t *uic_MainContainerSpeedData;
extern lv_obj_t *uic_MainContainerSpeedAlarmIndicator;
extern lv_obj_t *uic_MainPanelSpeedAlarmIndicatorIcon;
extern lv_obj_t *uic_MainLabelSpeedValue;
extern lv_obj_t *uic_MainLabelSpeedUnit;
extern lv_obj_t *uic_MainContainerBottom;
extern lv_obj_t *uic_MainContainerLimit;
extern lv_obj_t *uic_MainContainerLimitTitleLabel;
extern lv_obj_t *uic_MainLabelLimitTitle;
extern lv_obj_t *uic_MainContainerLimitData;
extern lv_obj_t *uic_MainContainerLimitIndicators1;
extern lv_obj_t *uic_MainLabelLimitIndicator1;
extern lv_obj_t *uic_MainPanelLimitIndicatorIcon1;
extern lv_obj_t *uic_MainContainerLimitIndicators2;
extern lv_obj_t *uic_MainLabelLimitIndicator2;
extern lv_obj_t *uic_MainPanelLimitIndicatorIcon2;
extern lv_obj_t *uic_MainContainerPullStateControls;
extern lv_obj_t *uic_MainButtonStage;
extern lv_obj_t *uic_MainLabelButtonStage;
extern lv_obj_t *uic_MainButtonStaged;
extern lv_obj_t *uic_MainLabelButtonStaged;
extern lv_obj_t *uic_MainLabelButtonStagedCancel;
extern lv_obj_t *uic_MainButtonStop;
extern lv_obj_t *uic_MainLabelButtonStop;
extern lv_obj_t *uic_MainContainerRelays;
extern lv_obj_t *uic_MainContainerRelaysTitleLabel;
extern lv_obj_t *uic_MainLabelRelaysTitle;
extern lv_obj_t *uic_MainContainerRelaysData;
extern lv_obj_t *uic_MainContainerRelayIndicators1;
extern lv_obj_t *uic_MainLabelRelayIndicator1;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon1;
extern lv_obj_t *uic_MainContainerRelayIndicators2;
extern lv_obj_t *uic_MainLabelRelayIndicator2;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon2;
extern lv_obj_t *uic_MainContainerRelayIndicators3;
extern lv_obj_t *uic_MainLabelRelayIndicator3;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon3;
extern lv_obj_t *uic_MainContainerRelayIndicators4;
extern lv_obj_t *uic_MainLabelRelayIndicator4;
extern lv_obj_t *uic_MainPanelRelayIndicatorIcon4;

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
void ui_event_ScreenSettings( lv_event_t * e);
extern lv_obj_t *ui_ScreenSettings;
extern lv_obj_t *ui_SettingsTabviewSettingsView;
extern lv_obj_t *ui_SettingsTabpageGeneral;
extern lv_obj_t *ui_SettingsPanelUnitsSelection;
extern lv_obj_t *ui_SettingsLabelUnitsMetric;
extern lv_obj_t *ui_SettingsSwitchUnits;
extern lv_obj_t *ui_SettingsLabelUnitsImperial;
extern lv_obj_t *ui_SettingsTabpageSpeed_and_Distance;
extern lv_obj_t *ui_SettingsTabpageTach;
extern lv_obj_t *ui_SettingsTabpageRelays_and_Limits;
extern lv_obj_t *ui_SettingsPanelConnectionRLM;
extern lv_obj_t *ui_SettingsContainerContainer8;
extern lv_obj_t *ui_SettingsContainerContainer9;
extern lv_obj_t *ui_SettingsButtonButton1;
extern lv_obj_t *ui_SettingsLabelLabel6;
extern lv_obj_t *ui_SettingsLabelLabel7;
extern lv_obj_t *ui_SettingsPanelRelayLimitSettings;
extern lv_obj_t *ui_SettingsContainerRelaySettings;
extern lv_obj_t *ui_SettingsLabellblRelays;
extern lv_obj_t *ui_SettingsContainercontainerEnableRelay;
extern lv_obj_t *ui_SettingsSwitchSwitch1;
extern lv_obj_t *ui_SettingsLabelLabel1;
extern lv_obj_t *ui_SettingsContainerrealayversion1;
extern lv_obj_t *ui_SettingsContainercontainterRelaySwitch1;
extern lv_obj_t *ui_SettingsLabelLabel21;
extern lv_obj_t *ui_SettingsSwitchSwitch3;
extern lv_obj_t *ui_SettingsDropdownDropdown1;
extern lv_obj_t *ui_SettingsDropdownDropdown2;
extern lv_obj_t *ui_SettingsContainercontainterRelaySwitch2;
extern lv_obj_t *ui_SettingsLabelLabel5;
extern lv_obj_t *ui_SettingsSwitchSwitch2;
extern lv_obj_t *ui_SettingsDropdownDropdown3;
extern lv_obj_t *ui_SettingsDropdownDropdown4;
extern lv_obj_t *ui_SettingsContainercontainterRelaySwitch3;
extern lv_obj_t *ui_SettingsLabelLabel8;
extern lv_obj_t *ui_SettingsSwitchSwitch5;
extern lv_obj_t *ui_SettingsDropdownDropdown5;
extern lv_obj_t *ui_SettingsDropdownDropdown6;
extern lv_obj_t *ui_SettingsContainercontainterRelaySwitch4;
extern lv_obj_t *ui_SettingsLabelLabel9;
extern lv_obj_t *ui_SettingsSwitchSwitch6;
extern lv_obj_t *ui_SettingsDropdownDropdown7;
extern lv_obj_t *ui_SettingsDropdownDropdown8;
extern lv_obj_t *ui_SettingsContainercontainerLimitSettings;
extern lv_obj_t *ui_SettingsLabelLabel2;
extern lv_obj_t *ui_SettingsContainercontainerEnableLimit;
extern lv_obj_t *ui_SettingsSwitchSwitch4;
extern lv_obj_t *ui_SettingsLabelLabel3;
extern lv_obj_t *ui_SettingsPanelPanel1;
extern lv_obj_t *ui_SettingsTabpageJudge;
extern lv_obj_t *ui_SettingsTabpageSafety_and_Displays;
extern lv_obj_t *ui_SettingsTabpageAbout;
extern lv_obj_t *ui_SettingsPanelAboutInfo;
extern lv_obj_t *ui_SettingsLabelAboutTitle;
extern lv_obj_t *ui_SettingsLabelVersionTitle;
extern lv_obj_t *ui_SettingsLabelVersionData;
extern lv_obj_t *ui_SettingsLabelBuildDateTitle;
extern lv_obj_t *ui_SettingsLabelBuildDateData;
extern lv_obj_t *ui_SettingsLabelDevelopedByTitle;
extern lv_obj_t *ui_SettingsLabelDevelopedByData;
extern lv_obj_t *ui_SettingsLabelInfoTitle;
extern lv_obj_t *ui_SettingsLabelInfoData;
extern lv_obj_t *ui_SettingsLabelSupportTitle;
extern lv_obj_t *ui_SettingsLabelSupportData;
extern lv_obj_t *ui_SettingsLabelCopyrightData;
void ui_event_SettingsTabpageExit( lv_event_t * e);
extern lv_obj_t *ui_SettingsTabpageExit;
void ui_event_SettingsContainerExitButtonOverlay( lv_event_t * e);
extern lv_obj_t *ui_SettingsContainerExitButtonOverlay;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenSettings;
extern lv_obj_t *uic_SettingsTabviewSettingsView;
extern lv_obj_t *uic_SettingsPanelUnitsSelection;
extern lv_obj_t *uic_SettingsLabelUnitsMetric;
extern lv_obj_t *uic_SettingsSwitchUnits;
extern lv_obj_t *uic_SettingsLabelUnitsImperial;
extern lv_obj_t *uic_SettingsPanelConnectionRLM;
extern lv_obj_t *uic_SettingsPanelRelayLimitSettings;
extern lv_obj_t *uic_SettingsContainerRelaySettings;
extern lv_obj_t *uic_SettingsLabellblRelays;
extern lv_obj_t *uic_SettingsContainercontainerEnableRelay;
extern lv_obj_t *uic_SettingsContainercontainterRelaySwitch1;
extern lv_obj_t *uic_SettingsContainercontainerLimitSettings;
extern lv_obj_t *uic_SettingsContainercontainerEnableLimit;
extern lv_obj_t *uic_SettingsPanelAboutInfo;
extern lv_obj_t *uic_SettingsLabelAboutTitle;
extern lv_obj_t *uic_SettingsLabelVersionTitle;
extern lv_obj_t *uic_SettingsLabelVersionData;
extern lv_obj_t *uic_SettingsLabelBuildDateTitle;
extern lv_obj_t *uic_SettingsLabelBuildDateData;
extern lv_obj_t *uic_SettingsLabelDevelopedByTitle;
extern lv_obj_t *uic_SettingsLabelDevelopedByData;
extern lv_obj_t *uic_SettingsLabelInfoTitle;
extern lv_obj_t *uic_SettingsLabelInfoData;
extern lv_obj_t *uic_SettingsLabelSupportData;
extern lv_obj_t *uic_SettingsLabelCopyrightData;
extern lv_obj_t *uic_SettingsContainerExitButtonOverlay;

// EVENTS
extern lv_obj_t *ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_iconsettings44px_png);   // assets/iconSettings44px.png
LV_IMG_DECLARE( ui_img_iconchangedriver44px_png);   // assets/iconChangeDriver44px.png

// FONTS
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_10);
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_6);
LV_FONT_DECLARE( ui_font_BIO_BOLDITALIC_8);
LV_FONT_DECLARE( ui_font_BIO_EXTRABOLD_19);
LV_FONT_DECLARE( ui_font_BIO_SEMIBOLD_6);
LV_FONT_DECLARE( ui_font_BIO_SEMIBOLD_7);
LV_FONT_DECLARE( ui_font_HH13);
LV_FONT_DECLARE( ui_font_HH24);
LV_FONT_DECLARE( ui_font_HH40);
LV_FONT_DECLARE( ui_font_HH8);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
