// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loadMainScreen(lv_event_t * e);
void MainScreenPresetButtonClicked(lv_event_t * e);
void DriverButton(lv_event_t * e);
void READYStageBtnPressed(lv_event_t * e);
void STAGEDCancelBtnPressed(lv_event_t * e);
void PULLINGStopBtnPressed(lv_event_t * e);
void PULLENDDiscardBtnPressed(lv_event_t * e);
void PULLENDSaveBtnPressed(lv_event_t * e);
void EMERGENCYSTOPResetBtnPressed(lv_event_t * e);
void SettingsScreenLoaded(lv_event_t * e);
void CreateDeviceTable(lv_event_t * e);
void Settings1Screen_OnLoad(lv_event_t * e);
void Settings1Screen_OnUnload(lv_event_t * e);
void SettingsUnitIDText(lv_event_t * e);
void SettingsSwitchJudgeChange(lv_event_t * e);
void EnableJudgeHelpButtonPressed(lv_event_t * e);
void SettingsSwitchUnitsChange(lv_event_t * e);
void SettingsSliderBrightnessChange(lv_event_t * e);
void SettingsTrackLengthText(lv_event_t * e);
void SettingsSwitchTachChange(lv_event_t * e);
void EnableTachHelpButtonPressed(lv_event_t * e);
void SettingsSwitchLimitChange(lv_event_t * e);
void EnableLimitsHelpButtonPressed(lv_event_t * e);
void SettingsSwitchRelaysChange(lv_event_t * e);
void EnableRelayHelpButtonPressed(lv_event_t * e);
void SettingsSwitchRotateScreen(lv_event_t * e);
void SettingsSwitchHelpIconVisibility(lv_event_t * e);
void RecalibrateTouch(lv_event_t * e);
void CalibrationNumberChanged(lv_event_t * e);
void SaveCalibrationNumberButton(lv_event_t * e);
void HELPCalNumber(lv_event_t * e);
void StartAutoDriveButtonPressed(lv_event_t * e);
void FinishAutoDriveButtonPressed(lv_event_t * e);
void SaveCalibrationAutoDriveNumberButton(lv_event_t * e);
void HELPAutoCal(lv_event_t * e);
void SaveRadarCalibration(lv_event_t * e);
void SaveGPSCalibration(lv_event_t * e);
void HELPPresetCalNumber(lv_event_t * e);
void SettingsSwitchAutoConnectTach(lv_event_t * e);
void HELPTachAutoConnect(lv_event_t * e);
void AlarmPresetValueChanged(lv_event_t * e);
void HELPAlarmPresets(lv_event_t * e);
void AlarmDXToggle1(lv_event_t * e);
void AlarmDXTripPointChange1(lv_event_t * e);
void AlarmDXTripStyleChange1(lv_event_t * e);
void AlarmDXColorChange1(lv_event_t * e);
void AlarmDXToggle2(lv_event_t * e);
void AlarmDXTripPointChange2(lv_event_t * e);
void AlarmDXTripStyleChange2(lv_event_t * e);
void AlarmDXColorChange2(lv_event_t * e);
void AlarmSpeedToggle1(lv_event_t * e);
void AlarmSpeedTripPointChange1(lv_event_t * e);
void AlarmSpeedTripStyleChange1(lv_event_t * e);
void AlarmSpeedColorChange1(lv_event_t * e);
void AlarmSpeedToggle2(lv_event_t * e);
void AlarmSpeedTripPointChange2(lv_event_t * e);
void AlarmSpeedTripStyleChange2(lv_event_t * e);
void AlarmSpeedColorChange2(lv_event_t * e);
void AlarmRPMToggle1(lv_event_t * e);
void AlarmRPMTripPointChange1(lv_event_t * e);
void AlarmRPMTripStyleChange1(lv_event_t * e);
void AlarmRPMColorChange1(lv_event_t * e);
void AlarmRPMToggle2(lv_event_t * e);
void AlarmRPMTripPointChange2(lv_event_t * e);
void AlarmRPMTripStyleChange2(lv_event_t * e);
void AlarmRPMColorChange2(lv_event_t * e);
void enterRemotePairingModeBtnClicked(lv_event_t * e);
void endRemotePairingModeBtnClicked(lv_event_t * e);
void HELPRemotePair(lv_event_t * e);
void DeviceRowActionButtonCB1(lv_event_t * e);
void PullHistoryScreenLoaded(lv_event_t * e);
void deletePullHistoryButtonClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
