// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loadMainScreen(lv_event_t * e);
void READYStageBtnPressed(lv_event_t * e);
void STAGEDCancelBtnPressed(lv_event_t * e);
void PULLINGStopBtnPressed(lv_event_t * e);
void PULLENDDiscardBtnPressed(lv_event_t * e);
void PULLENDSaveBtnPressed(lv_event_t * e);
void EMERGENCYSTOPResetBtnPressed(lv_event_t * e);
void SettingsScreenLoaded(lv_event_t * e);
void SettingsSwitchUnitsChange(lv_event_t * e);
void SettingsSwitchBenchmarkChange(lv_event_t * e);
void SettingsSliderBrightnessChange(lv_event_t * e);
void SettingsTrackLengthText(lv_event_t * e);
void SettingsSwitchTachChange(lv_event_t * e);
void EnableTachHelpButtonPressed(lv_event_t * e);
void SettingsSwitchLimitChange(lv_event_t * e);
void EnableLimitsHelpButtonPressed(lv_event_t * e);
void SettingsSwitchRelaysChange(lv_event_t * e);
void EnableRelayHelpButtonPressed(lv_event_t * e);
void SettingsSwitchHelpIconVisibility(lv_event_t * e);
void RecalibrateTouch(lv_event_t * e);
void SaveCalibrationNumberButton(lv_event_t * e);
void HELPCalNumber(lv_event_t * e);
void CalculateCalibrationCalculatorNumberButton(lv_event_t * e);
void SaveCalibrationCalculatorNumberButton(lv_event_t * e);
void HELPGearToothCalc(lv_event_t * e);
void StartAutoDriveButtonPressed(lv_event_t * e);
void FinishAutoDriveButtonPressed(lv_event_t * e);
void SaveCalibrationAutoDriveNumberButton(lv_event_t * e);
void HELPAutoCal(lv_event_t * e);
void SaveRadarCalibration(lv_event_t * e);
void SaveGPSCalibration(lv_event_t * e);
void HELPPresetCalNumber(lv_event_t * e);
void HELPTachAutoConnect(lv_event_t * e);
void HELPAlarmPresets(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
