// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Orange[1] = {0xF06B00};
const ui_theme_variable_t _ui_theme_alpha_Orange[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x1FA709};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};

const ui_theme_variable_t _ui_theme_color_Yellow[1] = {0xFFDE00};
const ui_theme_variable_t _ui_theme_alpha_Yellow[1] = {255};

const ui_theme_variable_t _ui_theme_color_Red[1] = {0xA70909};
const ui_theme_variable_t _ui_theme_alpha_Red[1] = {255};

const ui_theme_variable_t _ui_theme_color_Blue[1] = {0x346DE1};
const ui_theme_variable_t _ui_theme_alpha_Blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Dolphin[1] = {0xEEEEEE};
const ui_theme_variable_t _ui_theme_alpha_Dolphin[1] = {255};

const ui_theme_variable_t _ui_theme_color_indicGREEN[1] = {0x00FF05};
const ui_theme_variable_t _ui_theme_alpha_indicGREEN[1] = {255};

const ui_theme_variable_t _ui_theme_color_indicRED[1] = {0xFF0000};
const ui_theme_variable_t _ui_theme_alpha_indicRED[1] = {255};

const ui_theme_variable_t _ui_theme_color_indicDisabled[1] = {0xC2C2C2};
const ui_theme_variable_t _ui_theme_alpha_indicDisabled[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

