// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: M4_MCU_2025

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_ORANGE 0
#define UI_THEME_COLOR_GREEN 1
#define UI_THEME_COLOR_YELLOW 2
#define UI_THEME_COLOR_RED 3
#define UI_THEME_COLOR_BLUE 4
#define UI_THEME_COLOR_DOLPHIN 5
#define UI_THEME_COLOR_INDICGREEN 6
#define UI_THEME_COLOR_INDICRED 7
#define UI_THEME_COLOR_INDICDISABLED 8

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Orange[1];
extern const ui_theme_variable_t _ui_theme_alpha_Orange[1];

extern const ui_theme_variable_t _ui_theme_color_Green[1];
extern const ui_theme_variable_t _ui_theme_alpha_Green[1];

extern const ui_theme_variable_t _ui_theme_color_Yellow[1];
extern const ui_theme_variable_t _ui_theme_alpha_Yellow[1];

extern const ui_theme_variable_t _ui_theme_color_Red[1];
extern const ui_theme_variable_t _ui_theme_alpha_Red[1];

extern const ui_theme_variable_t _ui_theme_color_Blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Blue[1];

extern const ui_theme_variable_t _ui_theme_color_Dolphin[1];
extern const ui_theme_variable_t _ui_theme_alpha_Dolphin[1];

extern const ui_theme_variable_t _ui_theme_color_indicGREEN[1];
extern const ui_theme_variable_t _ui_theme_alpha_indicGREEN[1];

extern const ui_theme_variable_t _ui_theme_color_indicRED[1];
extern const ui_theme_variable_t _ui_theme_alpha_indicRED[1];

extern const ui_theme_variable_t _ui_theme_color_indicDisabled[1];
extern const ui_theme_variable_t _ui_theme_alpha_indicDisabled[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
